use crate::node::NodeInfo;
use crate::parser::{Field, FieldType, Function};

/// Strips namespaces
fn bare(name: &str) -> &str {
    name.rsplit("::").next().unwrap_or(name)
}

/// Strips the m_ member prefix
fn lua_field_name(name: &str) -> &str {
    name.strip_prefix("m_").unwrap_or(name)
}

fn has_color_attr(field: &Field) -> bool {
    field.attributes.iter().any(|a| a.name == "Color")
}

/// Lua type of a reflected field
fn field_lua_type(field: &Field) -> String {
    let base = match field.field_type {
        FieldType::Bool => "boolean".to_string(),
        FieldType::Int => "integer".to_string(),
        FieldType::Float | FieldType::Double => "number".to_string(),
        FieldType::String => "string".to_string(),
        FieldType::Vec2 => "vec2".to_string(),
        FieldType::Vec3 => if has_color_attr(field) { "color3" } else { "vec3" }.to_string(),
        FieldType::Vec4 => if has_color_attr(field) { "color4" } else { "vec4" }.to_string(),
        FieldType::Quaternion => "quat".to_string(),
        FieldType::Uid => uid_lua_type(&field.typename),
    };
    if field.is_array {
        format!("{base}[]")
    } else {
        base
    }
}

/// Lua type of a Box<T> and AssetHandle<T> field
fn uid_lua_type(typename: &str) -> String {
    let inner = typename
        .trim_start_matches("std::vector<")
        .trim_end_matches('>');
    if let Some(node_type) = inner.strip_prefix("Box<") {
        return bare(node_type.trim_end_matches('>')).to_string();
    }
    if inner.contains("AssetHandle<") {
        return "Asset".to_string();
    }
    "any".to_string()
}

/// Lua type of a method parameter or return
fn cpp_lua_type(cpp: &str) -> String {
    let t = cpp.trim();
    if t.contains("Box<") {
        let inner = t.split("Box<").nth(1).unwrap_or("Node");
        return bare(inner.trim_end_matches(['>', '&', ' '])).to_string();
    }
    if t.contains("AssetHandle<") {
        return "Asset".to_string();
    }
    if t.contains("bool") {
        return "boolean".to_string();
    }
    if t.contains("float") || t.contains("double") {
        return "number".to_string();
    }
    if t.contains("string") {
        return "string".to_string();
    }
    if t.contains("vec4") {
        return "vec4".to_string();
    }
    if t.contains("vec3") {
        return "vec3".to_string();
    }
    if t.contains("vec2") {
        return "vec2".to_string();
    }
    if t.contains("quat") {
        return "quat".to_string();
    }
    if t == "void" {
        return "nil".to_string();
    }
    if t.contains("int") || t.contains("long") || t.contains("short") || t == "char" {
        return "integer".to_string();
    }
    "any".to_string()
}

fn method_signature(class_name: &str, method: &Function) -> String {
    let mut params = format!("self: {class_name}");
    for p in &method.parameters {
        let optional = if p.default.is_some() { "?" } else { "" };
        params.push_str(&format!(", {}{optional}: {}", p.name, cpp_lua_type(&p.type_name)));
    }
    let ret = cpp_lua_type(&method.return_type);
    if ret == "nil" {
        format!("fun({params})")
    } else {
        format!("fun({params}): {ret}")
    }
}

fn emit_fields(out: &mut String, fields: &[Field]) {
    for f in fields {
        // Hidden fields don't appear in the inspector and shadow builtins like uid()/name()
        if f.attributes.iter().any(|a| a.name == "Hidden") {
            continue;
        }
        out.push_str(&format!(
            "---@field {} {}\n",
            lua_field_name(&f.name),
            field_lua_type(f)
        ));
    }
}

/// Renders the full types.d.lua contents for the reflected node set
pub fn generate_lua_stubs(nodes: &[NodeInfo]) -> String {
    let mut out = String::new();
    out.push_str("---@meta\n");
    out.push_str("-- Generated by the reflection generator; do not edit.\n");
    out.push_str("-- One class per reflected node type: fields, methods and the global type marker.\n\n");

    for node in nodes {
        let class_name = node.name.clone();
        let parent = node
            .parent
            .as_ref()
            .map(|p| format!(" : {}", bare(&p.name)))
            .unwrap_or_default();

        out.push_str(&format!("---@class {class_name}{parent}\n"));

        emit_fields(&mut out, &node.global_fields);
        for group in &node.groups {
            emit_fields(&mut out, &group.fields);
            for sub in &group.subgroups {
                emit_fields(&mut out, &sub.fields);
            }
        }

        for method in &node.methods {
            out.push_str(&format!(
                "---@field {} {}\n",
                method.name,
                method_signature(&class_name, method)
            ));
        }

        out.push_str(&format!("\n---@type TypeMarker\n{class_name} = nil\n\n"));
    }

    out
}
