var annotated_dup =
[
    [ "assets", null, [
      [ "_detail", null, [
        [ "MeshFileHeader", "structassets_1_1__detail_1_1MeshFileHeader.html", null ],
        [ "NodeFileBinaryHeader", "structassets_1_1__detail_1_1NodeFileBinaryHeader.html", null ],
        [ "VoxelFileHeader", "structassets_1_1__detail_1_1VoxelFileHeader.html", null ]
      ] ],
      [ "Action", "classassets_1_1Action.html", "classassets_1_1Action" ],
      [ "Animation", "classassets_1_1Animation.html", "classassets_1_1Animation" ],
      [ "AnimationClip", "structassets_1_1AnimationClip.html", "structassets_1_1AnimationClip" ],
      [ "AnimationTrack", "structassets_1_1AnimationTrack.html", "structassets_1_1AnimationTrack" ],
      [ "Asset", "classassets_1_1Asset.html", null ],
      [ "AssetInfo", "structassets_1_1AssetInfo.html", null ],
      [ "AssetManager", "classassets_1_1AssetManager.html", "classassets_1_1AssetManager" ],
      [ "AssetRegistry", "classassets_1_1AssetRegistry.html", null ],
      [ "AudioBank", "classassets_1_1AudioBank.html", null ],
      [ "AudioBus", "classassets_1_1AudioBus.html", null ],
      [ "AudioEvent", "classassets_1_1AudioEvent.html", null ],
      [ "AudioPort", "classassets_1_1AudioPort.html", null ],
      [ "AudioSnapshot", "classassets_1_1AudioSnapshot.html", null ],
      [ "AudioStrings", "classassets_1_1AudioStrings.html", null ],
      [ "AudioVca", "classassets_1_1AudioVca.html", null ],
      [ "BrickEntry", "structassets_1_1BrickEntry.html", "structassets_1_1BrickEntry" ],
      [ "BrickPool", "classassets_1_1BrickPool.html", "classassets_1_1BrickPool" ],
      [ "ColorScheme", "classassets_1_1ColorScheme.html", "classassets_1_1ColorScheme" ],
      [ "Curve", "classassets_1_1Curve.html", "classassets_1_1Curve" ],
      [ "Data", "classassets_1_1Data.html", "classassets_1_1Data" ],
      [ "DataValue", "classassets_1_1DataValue.html", "classassets_1_1DataValue" ],
      [ "DestructionMaterial", "classassets_1_1DestructionMaterial.html", "classassets_1_1DestructionMaterial" ],
      [ "Font", "classassets_1_1Font.html", null ],
      [ "Handle", "classassets_1_1Handle.html", "classassets_1_1Handle" ],
      [ "HandleBase", "classassets_1_1HandleBase.html", "classassets_1_1HandleBase" ],
      [ "Haptic", "classassets_1_1Haptic.html", "classassets_1_1Haptic" ],
      [ "HdrImage", "structassets_1_1HdrImage.html", "structassets_1_1HdrImage" ],
      [ "ImageLocalization", "classassets_1_1ImageLocalization.html", null ],
      [ "InputLayout", "classassets_1_1InputLayout.html", "classassets_1_1InputLayout" ],
      [ "InputSettings", "classassets_1_1InputSettings.html", "classassets_1_1InputSettings" ],
      [ "ISaveable", "classassets_1_1ISaveable.html", null ],
      [ "LatticeOrientation", "structassets_1_1LatticeOrientation.html", null ],
      [ "LatticePlacement", "structassets_1_1LatticePlacement.html", null ],
      [ "Localization", "classassets_1_1Localization.html", null ],
      [ "LocalizationBase", "classassets_1_1LocalizationBase.html", null ],
      [ "Material", "classassets_1_1Material.html", "classassets_1_1Material" ],
      [ "MaterialInstance", "classassets_1_1MaterialInstance.html", "classassets_1_1MaterialInstance" ],
      [ "MaterialSettings", "structassets_1_1MaterialSettings.html", null ],
      [ "Mesh", "classassets_1_1Mesh.html", "classassets_1_1Mesh" ],
      [ "NamedSchemaEntry", "structassets_1_1NamedSchemaEntry.html", null ],
      [ "NodePose", "structassets_1_1NodePose.html", null ],
      [ "PackArchive", "classassets_1_1PackArchive.html", null ],
      [ "Palette", "structassets_1_1Palette.html", null ],
      [ "PaletteEntry", "structassets_1_1PaletteEntry.html", "structassets_1_1PaletteEntry" ],
      [ "Paths", "structassets_1_1Paths.html", "structassets_1_1Paths" ],
      [ "PhysicsMaterial", "classassets_1_1PhysicsMaterial.html", null ],
      [ "Prefab", "classassets_1_1Prefab.html", "classassets_1_1Prefab" ],
      [ "Schema", "classassets_1_1Schema.html", "classassets_1_1Schema" ],
      [ "SchemaField", "structassets_1_1SchemaField.html", "structassets_1_1SchemaField" ],
      [ "Script", "classassets_1_1Script.html", "classassets_1_1Script" ],
      [ "Shader", "classassets_1_1Shader.html", "classassets_1_1Shader" ],
      [ "Skin", "structassets_1_1Skin.html", "structassets_1_1Skin" ],
      [ "Texture", "classassets_1_1Texture.html", null ],
      [ "TypeSwitch", "structassets_1_1TypeSwitch.html", "structassets_1_1TypeSwitch" ],
      [ "TypeSwitchCase", "structassets_1_1TypeSwitchCase.html", null ],
      [ "UIElement", "classassets_1_1UIElement.html", null ],
      [ "UIImage", "classassets_1_1UIImage.html", null ],
      [ "UIStyle", "classassets_1_1UIStyle.html", null ],
      [ "Volume", "classassets_1_1Volume.html", "classassets_1_1Volume" ],
      [ "VoxelMaterialSlot", "structassets_1_1VoxelMaterialSlot.html", null ],
      [ "VoxelModel", "classassets_1_1VoxelModel.html", "classassets_1_1VoxelModel" ],
      [ "VoxelPalette", "classassets_1_1VoxelPalette.html", "classassets_1_1VoxelPalette" ],
      [ "VoxIntermediateModel", "structassets_1_1VoxIntermediateModel.html", null ],
      [ "VoxIntermediates", "structassets_1_1VoxIntermediates.html", null ],
      [ "VoxModel", "structassets_1_1VoxModel.html", null ],
      [ "VoxNode", "structassets_1_1VoxNode.html", null ],
      [ "VoxPlacement", "structassets_1_1VoxPlacement.html", null ],
      [ "VoxScene", "structassets_1_1VoxScene.html", "structassets_1_1VoxScene" ],
      [ "VoxTransform", "structassets_1_1VoxTransform.html", null ],
      [ "VoxVoxel", "structassets_1_1VoxVoxel.html", "structassets_1_1VoxVoxel" ]
    ] ],
    [ "audio", null, [
      [ "AudioSystem", "classaudio_1_1AudioSystem.html", null ]
    ] ],
    [ "editor", "namespaceeditor.html", [
      [ "Assets", "namespaceeditor_1_1Assets.html", [
        [ "Importers", "namespaceeditor_1_1Assets_1_1Importers.html", [
          [ "AudioBankImporter", "classeditor_1_1Assets_1_1Importers_1_1AudioBankImporter.html", "classeditor_1_1Assets_1_1Importers_1_1AudioBankImporter" ],
          [ "AudioStringImporter", "classeditor_1_1Assets_1_1Importers_1_1AudioStringImporter.html", "classeditor_1_1Assets_1_1Importers_1_1AudioStringImporter" ],
          [ "CompactImportWindow", "classeditor_1_1Assets_1_1Importers_1_1CompactImportWindow.html", null ],
          [ "CompactImportWindowViewModel", "classeditor_1_1Assets_1_1Importers_1_1CompactImportWindowViewModel.html", null ],
          [ "FMODMetadata", "classeditor_1_1Assets_1_1Importers_1_1FMODMetadata.html", null ],
          [ "FontImporter", "classeditor_1_1Assets_1_1Importers_1_1FontImporter.html", "classeditor_1_1Assets_1_1Importers_1_1FontImporter" ],
          [ "GltfImporter", "classeditor_1_1Assets_1_1Importers_1_1GltfImporter.html", "classeditor_1_1Assets_1_1Importers_1_1GltfImporter" ],
          [ "IAssetImporter", "interfaceeditor_1_1Assets_1_1Importers_1_1IAssetImporter.html", "interfaceeditor_1_1Assets_1_1Importers_1_1IAssetImporter" ],
          [ "ImporterSettingsCardVM", "classeditor_1_1Assets_1_1Importers_1_1ImporterSettingsCardVM.html", null ],
          [ "ImportFileViewModel", "classeditor_1_1Assets_1_1Importers_1_1ImportFileViewModel.html", "classeditor_1_1Assets_1_1Importers_1_1ImportFileViewModel" ],
          [ "ImportFolderViewModel", "classeditor_1_1Assets_1_1Importers_1_1ImportFolderViewModel.html", "classeditor_1_1Assets_1_1Importers_1_1ImportFolderViewModel" ],
          [ "ImportNodeViewModel", "classeditor_1_1Assets_1_1Importers_1_1ImportNodeViewModel.html", null ],
          [ "ImportTreeState", "classeditor_1_1Assets_1_1Importers_1_1ImportTreeState.html", null ],
          [ "ImportWindow", "classeditor_1_1Assets_1_1Importers_1_1ImportWindow.html", null ],
          [ "ImportWindowViewModel", "classeditor_1_1Assets_1_1Importers_1_1ImportWindowViewModel.html", null ],
          [ "PsdImporter", "classeditor_1_1Assets_1_1Importers_1_1PsdImporter.html", "classeditor_1_1Assets_1_1Importers_1_1PsdImporter" ],
          [ "SettingFieldVM", "classeditor_1_1Assets_1_1Importers_1_1SettingFieldVM.html", null ],
          [ "TextureImporter", "classeditor_1_1Assets_1_1Importers_1_1TextureImporter.html", "classeditor_1_1Assets_1_1Importers_1_1TextureImporter" ],
          [ "UIImageImporter", "classeditor_1_1Assets_1_1Importers_1_1UIImageImporter.html", "classeditor_1_1Assets_1_1Importers_1_1UIImageImporter" ],
          [ "VoxImporter", "classeditor_1_1Assets_1_1Importers_1_1VoxImporter.html", "classeditor_1_1Assets_1_1Importers_1_1VoxImporter" ]
        ] ],
        [ "Types", "namespaceeditor_1_1Assets_1_1Types.html", [
          [ "AnimationAsset", "classeditor_1_1Assets_1_1Types_1_1AnimationAsset.html", null ],
          [ "AudioBankAsset", "classeditor_1_1Assets_1_1Types_1_1AudioBankAsset.html", null ],
          [ "AudioBusAsset", "classeditor_1_1Assets_1_1Types_1_1AudioBusAsset.html", null ],
          [ "AudioEventAsset", "classeditor_1_1Assets_1_1Types_1_1AudioEventAsset.html", null ],
          [ "AudioPortAsset", "classeditor_1_1Assets_1_1Types_1_1AudioPortAsset.html", null ],
          [ "AudioSnapshot", "classeditor_1_1Assets_1_1Types_1_1AudioSnapshot.html", null ],
          [ "AudioStringsAsset", "classeditor_1_1Assets_1_1Types_1_1AudioStringsAsset.html", null ],
          [ "BaseAsset", "classeditor_1_1Assets_1_1Types_1_1BaseAsset.html", "classeditor_1_1Assets_1_1Types_1_1BaseAsset" ],
          [ "ColorSchemeAsset", "classeditor_1_1Assets_1_1Types_1_1ColorSchemeAsset.html", null ],
          [ "CurveAsset", "classeditor_1_1Assets_1_1Types_1_1CurveAsset.html", null ],
          [ "DataAsset", "classeditor_1_1Assets_1_1Types_1_1DataAsset.html", null ],
          [ "DestructionMaterialAsset", "classeditor_1_1Assets_1_1Types_1_1DestructionMaterialAsset.html", null ],
          [ "FontAsset", "classeditor_1_1Assets_1_1Types_1_1FontAsset.html", null ],
          [ "HapticAsset", "classeditor_1_1Assets_1_1Types_1_1HapticAsset.html", null ],
          [ "ImageLocalizationAsset", "classeditor_1_1Assets_1_1Types_1_1ImageLocalizationAsset.html", null ],
          [ "InputActionAsset", "classeditor_1_1Assets_1_1Types_1_1InputActionAsset.html", null ],
          [ "InputLayoutAsset", "classeditor_1_1Assets_1_1Types_1_1InputLayoutAsset.html", null ],
          [ "LocalizationAsset", "classeditor_1_1Assets_1_1Types_1_1LocalizationAsset.html", null ],
          [ "MaterialAsset", "classeditor_1_1Assets_1_1Types_1_1MaterialAsset.html", null ],
          [ "MaterialInstanceAsset", "classeditor_1_1Assets_1_1Types_1_1MaterialInstanceAsset.html", null ],
          [ "MeshAsset", "classeditor_1_1Assets_1_1Types_1_1MeshAsset.html", null ],
          [ "NodeAsset", "classeditor_1_1Assets_1_1Types_1_1NodeAsset.html", null ],
          [ "PhysicsMaterialAsset", "classeditor_1_1Assets_1_1Types_1_1PhysicsMaterialAsset.html", null ],
          [ "ProjectSettingsAsset", "classeditor_1_1Assets_1_1Types_1_1ProjectSettingsAsset.html", null ],
          [ "SchemaAsset", "classeditor_1_1Assets_1_1Types_1_1SchemaAsset.html", null ],
          [ "ScriptAsset", "classeditor_1_1Assets_1_1Types_1_1ScriptAsset.html", null ],
          [ "ShaderAsset", "classeditor_1_1Assets_1_1Types_1_1ShaderAsset.html", null ],
          [ "TextureAsset", "classeditor_1_1Assets_1_1Types_1_1TextureAsset.html", null ],
          [ "UIElementAsset", "classeditor_1_1Assets_1_1Types_1_1UIElementAsset.html", null ],
          [ "UIImageAsset", "classeditor_1_1Assets_1_1Types_1_1UIImageAsset.html", null ],
          [ "UIStyleAsset", "classeditor_1_1Assets_1_1Types_1_1UIStyleAsset.html", null ],
          [ "VcaAsset", "classeditor_1_1Assets_1_1Types_1_1VcaAsset.html", null ],
          [ "VoxelModelAsset", "classeditor_1_1Assets_1_1Types_1_1VoxelModelAsset.html", null ],
          [ "VoxelPaletteAsset", "classeditor_1_1Assets_1_1Types_1_1VoxelPaletteAsset.html", null ]
        ] ],
        [ "AssetBrowserView", "classeditor_1_1Assets_1_1AssetBrowserView.html", null ],
        [ "AssetBrowserViewModel", "classeditor_1_1Assets_1_1AssetBrowserViewModel.html", null ],
        [ "AssetFile", "classeditor_1_1Assets_1_1AssetFile.html", null ],
        [ "AssetFolder", "classeditor_1_1Assets_1_1AssetFolder.html", "classeditor_1_1Assets_1_1AssetFolder" ],
        [ "AssetTag", "classeditor_1_1Assets_1_1AssetTag.html", null ],
        [ "AssetTagFilter", "classeditor_1_1Assets_1_1AssetTagFilter.html", null ],
        [ "AssetTypeFilter", "classeditor_1_1Assets_1_1AssetTypeFilter.html", null ],
        [ "AssetTypeFilterGroup", "classeditor_1_1Assets_1_1AssetTypeFilterGroup.html", null ],
        [ "BreadcrumbItem", "classeditor_1_1Assets_1_1BreadcrumbItem.html", null ],
        [ "Curve", "classeditor_1_1Assets_1_1Curve.html", null ],
        [ "CurveDto", "classeditor_1_1Assets_1_1CurveDto.html", null ],
        [ "GltfSectionDto", "classeditor_1_1Assets_1_1GltfSectionDto.html", null ],
        [ "Haptic", "classeditor_1_1Assets_1_1Haptic.html", null ],
        [ "IMetaSection", "interfaceeditor_1_1Assets_1_1IMetaSection.html", null ],
        [ "MetaFileDto", "classeditor_1_1Assets_1_1MetaFileDto.html", null ],
        [ "PointDto", "classeditor_1_1Assets_1_1PointDto.html", null ],
        [ "PsdSectionDto", "classeditor_1_1Assets_1_1PsdSectionDto.html", null ],
        [ "TextureSectionDto", "classeditor_1_1Assets_1_1TextureSectionDto.html", null ],
        [ "VoxelMaterialSlot", "classeditor_1_1Assets_1_1VoxelMaterialSlot.html", null ],
        [ "VoxelPaletteEntry", "classeditor_1_1Assets_1_1VoxelPaletteEntry.html", "classeditor_1_1Assets_1_1VoxelPaletteEntry" ],
        [ "VoxelPaletteFile", "classeditor_1_1Assets_1_1VoxelPaletteFile.html", null ],
        [ "VoxSectionDto", "classeditor_1_1Assets_1_1VoxSectionDto.html", null ]
      ] ],
      [ "Components", "namespaceeditor_1_1Components.html", [
        [ "Converters", "namespaceeditor_1_1Components_1_1Converters.html", [
          [ "ResourceBrushConverter", "classeditor_1_1Components_1_1Converters_1_1ResourceBrushConverter.html", null ]
        ] ],
        [ "CurveCanvas", "namespaceeditor_1_1Components_1_1CurveCanvas.html", [
          [ "CurveCanvas", "classeditor_1_1Components_1_1CurveCanvas_1_1CurveCanvas.html", null ],
          [ "CurveCanvasItem", "classeditor_1_1Components_1_1CurveCanvas_1_1CurveCanvasItem.html", null ]
        ] ],
        [ "Elements", "namespaceeditor_1_1Components_1_1Elements.html", [
          [ "ArrayBox", "classeditor_1_1Components_1_1Elements_1_1ArrayBox.html", null ],
          [ "AssetBox", "classeditor_1_1Components_1_1Elements_1_1AssetBox.html", null ],
          [ "BoolBox", "classeditor_1_1Components_1_1Elements_1_1BoolBox.html", null ],
          [ "Color3Box", "classeditor_1_1Components_1_1Elements_1_1Color3Box.html", null ],
          [ "Color4Box", "classeditor_1_1Components_1_1Elements_1_1Color4Box.html", null ],
          [ "ColorBoxBase", "classeditor_1_1Components_1_1Elements_1_1ColorBoxBase.html", null ],
          [ "DragFloatBox", "classeditor_1_1Components_1_1Elements_1_1DragFloatBox.html", null ],
          [ "DragIntBox", "classeditor_1_1Components_1_1Elements_1_1DragIntBox.html", null ],
          [ "DragNumberBoxBase", "classeditor_1_1Components_1_1Elements_1_1DragNumberBoxBase.html", null ],
          [ "DragVec2Box", "classeditor_1_1Components_1_1Elements_1_1DragVec2Box.html", null ],
          [ "DragVec3Box", "classeditor_1_1Components_1_1Elements_1_1DragVec3Box.html", null ],
          [ "DragVec4Box", "classeditor_1_1Components_1_1Elements_1_1DragVec4Box.html", null ],
          [ "DragVectorBoxBase", "classeditor_1_1Components_1_1Elements_1_1DragVectorBoxBase.html", null ],
          [ "EditorColorPalette", "classeditor_1_1Components_1_1Elements_1_1EditorColorPalette.html", null ],
          [ "EnumBox", "classeditor_1_1Components_1_1Elements_1_1EnumBox.html", null ],
          [ "IAsyncCanExecuteCommand", "interfaceeditor_1_1Components_1_1Elements_1_1IAsyncCanExecuteCommand.html", null ],
          [ "IRowSplittable", "interfaceeditor_1_1Components_1_1Elements_1_1IRowSplittable.html", null ],
          [ "IRowVisible", "interfaceeditor_1_1Components_1_1Elements_1_1IRowVisible.html", null ],
          [ "IStructRow", "interfaceeditor_1_1Components_1_1Elements_1_1IStructRow.html", null ],
          [ "NodeBox", "classeditor_1_1Components_1_1Elements_1_1NodeBox.html", null ],
          [ "SearchableTreeItem&lt; T &gt;", "classeditor_1_1Components_1_1Elements_1_1SearchableTreeItem-1-g.html", null ],
          [ "StringBox", "classeditor_1_1Components_1_1Elements_1_1StringBox.html", null ],
          [ "TagStrip", "classeditor_1_1Components_1_1Elements_1_1TagStrip.html", null ]
        ] ],
        [ "Modals", "namespaceeditor_1_1Components_1_1Modals.html", [
          [ "AboutWindow", "classeditor_1_1Components_1_1Modals_1_1AboutWindow.html", null ],
          [ "AssetFolderNode", "classeditor_1_1Components_1_1Modals_1_1AssetFolderNode.html", null ],
          [ "AssetFolderTree", "classeditor_1_1Components_1_1Modals_1_1AssetFolderTree.html", null ],
          [ "AssetFolderTreeViewModel", "classeditor_1_1Components_1_1Modals_1_1AssetFolderTreeViewModel.html", null ],
          [ "AssetList", "classeditor_1_1Components_1_1Modals_1_1AssetList.html", null ],
          [ "AssetListPickerViewModel", "classeditor_1_1Components_1_1Modals_1_1AssetListPickerViewModel.html", null ],
          [ "AssetPickerItem", "classeditor_1_1Components_1_1Modals_1_1AssetPickerItem.html", null ],
          [ "AssetTree", "classeditor_1_1Components_1_1Modals_1_1AssetTree.html", null ],
          [ "AssetTreeNode", "classeditor_1_1Components_1_1Modals_1_1AssetTreeNode.html", null ],
          [ "AssetTreeViewModel", "classeditor_1_1Components_1_1Modals_1_1AssetTreeViewModel.html", null ],
          [ "HierarchyDisplayItem", "classeditor_1_1Components_1_1Modals_1_1HierarchyDisplayItem.html", null ],
          [ "HierarchyPickerViewModel", "classeditor_1_1Components_1_1Modals_1_1HierarchyPickerViewModel.html", null ],
          [ "HierarchyTree", "classeditor_1_1Components_1_1Modals_1_1HierarchyTree.html", null ],
          [ "IModalService", "interfaceeditor_1_1Components_1_1Modals_1_1IModalService.html", null ],
          [ "LoaderTaskException", "classeditor_1_1Components_1_1Modals_1_1LoaderTaskException.html", null ],
          [ "LoaderViewModel", "classeditor_1_1Components_1_1Modals_1_1LoaderViewModel.html", null ],
          [ "MessageModal", "classeditor_1_1Components_1_1Modals_1_1MessageModal.html", "classeditor_1_1Components_1_1Modals_1_1MessageModal" ],
          [ "MessageModalViewModel", "classeditor_1_1Components_1_1Modals_1_1MessageModalViewModel.html", null ],
          [ "ModalService", "classeditor_1_1Components_1_1Modals_1_1ModalService.html", null ],
          [ "NewFolderModal", "classeditor_1_1Components_1_1Modals_1_1NewFolderModal.html", null ],
          [ "NodeDisplayItem", "classeditor_1_1Components_1_1Modals_1_1NodeDisplayItem.html", null ],
          [ "NodeTypePickerViewModel", "classeditor_1_1Components_1_1Modals_1_1NodeTypePickerViewModel.html", null ],
          [ "NodeTypeTree", "classeditor_1_1Components_1_1Modals_1_1NodeTypeTree.html", null ],
          [ "PickerViewModel", "classeditor_1_1Components_1_1Modals_1_1PickerViewModel.html", null ],
          [ "PickerWindow", "classeditor_1_1Components_1_1Modals_1_1PickerWindow.html", null ],
          [ "RenameModal", "classeditor_1_1Components_1_1Modals_1_1RenameModal.html", null ],
          [ "SaveFileModal", "classeditor_1_1Components_1_1Modals_1_1SaveFileModal.html", null ],
          [ "SaveFileViewModel", "classeditor_1_1Components_1_1Modals_1_1SaveFileViewModel.html", null ],
          [ "SimpleLoaderWindow", "classeditor_1_1Components_1_1Modals_1_1SimpleLoaderWindow.html", null ],
          [ "SplashLoaderWindow", "classeditor_1_1Components_1_1Modals_1_1SplashLoaderWindow.html", null ]
        ] ]
      ] ],
      [ "Converters", "namespaceeditor_1_1Converters.html", [
        [ "SeverityToColorConverter", "classeditor_1_1Converters_1_1SeverityToColorConverter.html", null ],
        [ "SeverityBarColorConverter", "classeditor_1_1Converters_1_1SeverityBarColorConverter.html", null ],
        [ "SeverityRowGradientConverter", "classeditor_1_1Converters_1_1SeverityRowGradientConverter.html", null ],
        [ "SeverityFillConverter", "classeditor_1_1Converters_1_1SeverityFillConverter.html", null ],
        [ "ToggleForegroundConverter", "classeditor_1_1Converters_1_1ToggleForegroundConverter.html", null ],
        [ "BoolFillConverter", "classeditor_1_1Converters_1_1BoolFillConverter.html", null ],
        [ "TraceForegroundConverter", "classeditor_1_1Converters_1_1TraceForegroundConverter.html", null ],
        [ "BoolToOpacityConverter", "classeditor_1_1Converters_1_1BoolToOpacityConverter.html", null ],
        [ "EnabledToColorConverter", "classeditor_1_1Converters_1_1EnabledToColorConverter.html", null ],
        [ "ScaleConverter", "classeditor_1_1Converters_1_1ScaleConverter.html", null ],
        [ "EnumEqualsConverter", "classeditor_1_1Converters_1_1EnumEqualsConverter.html", null ],
        [ "SnapValueConverter", "classeditor_1_1Converters_1_1SnapValueConverter.html", null ],
        [ "DockContentCornerRadiusConverter", "classeditor_1_1Converters_1_1DockContentCornerRadiusConverter.html", null ],
        [ "DockFocusBrushConverter", "classeditor_1_1Converters_1_1DockFocusBrushConverter.html", null ]
      ] ],
      [ "Editors", "namespaceeditor_1_1Editors.html", [
        [ "CurvePointVM", "classeditor_1_1Editors_1_1CurvePointVM.html", null ],
        [ "CurveView", "classeditor_1_1Editors_1_1CurveView.html", null ],
        [ "CurveViewModel", "classeditor_1_1Editors_1_1CurveViewModel.html", null ],
        [ "GenericFieldVM", "classeditor_1_1Editors_1_1GenericFieldVM.html", null ],
        [ "GenericView", "classeditor_1_1Editors_1_1GenericView.html", null ],
        [ "GenericViewModel", "classeditor_1_1Editors_1_1GenericViewModel.html", null ],
        [ "HapticsView", "classeditor_1_1Editors_1_1HapticsView.html", null ],
        [ "HapticsViewModel", "classeditor_1_1Editors_1_1HapticsViewModel.html", null ],
        [ "IToastZoneEditor", "interfaceeditor_1_1Editors_1_1IToastZoneEditor.html", null ],
        [ "PaletteSlotVM", "classeditor_1_1Editors_1_1PaletteSlotVM.html", null ],
        [ "PaletteSwatchVM", "classeditor_1_1Editors_1_1PaletteSwatchVM.html", null ],
        [ "PaletteView", "classeditor_1_1Editors_1_1PaletteView.html", null ],
        [ "PaletteViewModel", "classeditor_1_1Editors_1_1PaletteViewModel.html", "classeditor_1_1Editors_1_1PaletteViewModel" ],
        [ "SchemaFieldItemVM", "classeditor_1_1Editors_1_1SchemaFieldItemVM.html", null ],
        [ "SchemaView", "classeditor_1_1Editors_1_1SchemaView.html", null ],
        [ "SchemaViewModel", "classeditor_1_1Editors_1_1SchemaViewModel.html", null ],
        [ "StringOptionVM", "classeditor_1_1Editors_1_1StringOptionVM.html", null ],
        [ "StructTypeVM", "classeditor_1_1Editors_1_1StructTypeVM.html", null ],
        [ "TableCellVM", "classeditor_1_1Editors_1_1TableCellVM.html", null ],
        [ "TableRowVM", "classeditor_1_1Editors_1_1TableRowVM.html", null ],
        [ "TableView", "classeditor_1_1Editors_1_1TableView.html", null ],
        [ "TableViewModel", "classeditor_1_1Editors_1_1TableViewModel.html", null ],
        [ "TypeSwitchCaseVM", "classeditor_1_1Editors_1_1TypeSwitchCaseVM.html", null ]
      ] ],
      [ "Engine", "namespaceeditor_1_1Engine.html", [
        [ "Listener", "classeditor_1_1Engine_1_1Listener.html", null ],
        [ "NodeTreeItem", "classeditor_1_1Engine_1_1NodeTreeItem.html", null ],
        [ "SettingDescriptor", "classeditor_1_1Engine_1_1SettingDescriptor.html", "classeditor_1_1Engine_1_1SettingDescriptor" ],
        [ "ToastEngine", "classeditor_1_1Engine_1_1ToastEngine.html", "classeditor_1_1Engine_1_1ToastEngine" ],
        [ "ToastViewportFrame", "structeditor_1_1Engine_1_1ToastViewportFrame.html", null ],
        [ "WorkspaceResult", "structeditor_1_1Engine_1_1WorkspaceResult.html", null ]
      ] ],
      [ "Logger", "namespaceeditor_1_1Logger.html", [
        [ "LogClient", "classeditor_1_1Logger_1_1LogClient.html", null ],
        [ "LogDetailWindow", "classeditor_1_1Logger_1_1LogDetailWindow.html", null ],
        [ "LogEntry", "classeditor_1_1Logger_1_1LogEntry.html", null ],
        [ "LogFilterState", "classeditor_1_1Logger_1_1LogFilterState.html", null ],
        [ "LogsView", "classeditor_1_1Logger_1_1LogsView.html", null ],
        [ "LogsViewModel", "classeditor_1_1Logger_1_1LogsViewModel.html", null ],
        [ "ReverseLogList", "classeditor_1_1Logger_1_1ReverseLogList.html", null ],
        [ "ScrollMarkerOverlay", "classeditor_1_1Logger_1_1ScrollMarkerOverlay.html", null ],
        [ "SeverityFilterViewModel", "classeditor_1_1Logger_1_1SeverityFilterViewModel.html", null ],
        [ "SinkFilterViewModel", "classeditor_1_1Logger_1_1SinkFilterViewModel.html", null ]
      ] ],
      [ "StartWindow", "namespaceeditor_1_1StartWindow.html", [
        [ "NewProjectWindow", "classeditor_1_1StartWindow_1_1NewProjectWindow.html", null ],
        [ "ProjectList", "classeditor_1_1StartWindow_1_1ProjectList.html", null ],
        [ "ProjectListItem", "structeditor_1_1StartWindow_1_1ProjectListItem.html", null ],
        [ "StartWindow", "classeditor_1_1StartWindow_1_1StartWindow.html", null ],
        [ "StartWindowViewModel", "classeditor_1_1StartWindow_1_1StartWindowViewModel.html", null ]
      ] ],
      [ "VoxelEditor", "namespaceeditor_1_1VoxelEditor.html", [
        [ "PaletteEntryVM", "classeditor_1_1VoxelEditor_1_1PaletteEntryVM.html", null ],
        [ "VoxelEditorView", "classeditor_1_1VoxelEditor_1_1VoxelEditorView.html", null ],
        [ "VoxelEditorViewModel", "classeditor_1_1VoxelEditor_1_1VoxelEditorViewModel.html", null ],
        [ "VoxelEditorWindow", "classeditor_1_1VoxelEditor_1_1VoxelEditorWindow.html", null ],
        [ "VoxelOrthoView", "classeditor_1_1VoxelEditor_1_1VoxelOrthoView.html", null ],
        [ "VoxelPalettePicker", "classeditor_1_1VoxelEditor_1_1VoxelPalettePicker.html", null ]
      ] ],
      [ "Workspace", "namespaceeditor_1_1Workspace.html", [
        [ "AssetBrowserSettingsViewModel", "classeditor_1_1Workspace_1_1AssetBrowserSettingsViewModel.html", null ],
        [ "AutosaveService", "classeditor_1_1Workspace_1_1AutosaveService.html", null ],
        [ "BoolSettingRow", "classeditor_1_1Workspace_1_1BoolSettingRow.html", null ],
        [ "ButtonVM", "classeditor_1_1Workspace_1_1ButtonVM.html", null ],
        [ "ClassCardVM", "classeditor_1_1Workspace_1_1ClassCardVM.html", null ],
        [ "DockFactory", "classeditor_1_1Workspace_1_1DockFactory.html", "classeditor_1_1Workspace_1_1DockFactory" ],
        [ "EditorHostWindow", "classeditor_1_1Workspace_1_1EditorHostWindow.html", null ],
        [ "EnumSettingRow", "classeditor_1_1Workspace_1_1EnumSettingRow.html", null ],
        [ "FieldVM", "classeditor_1_1Workspace_1_1FieldVM.html", null ],
        [ "FloatSettingRow", "classeditor_1_1Workspace_1_1FloatSettingRow.html", "classeditor_1_1Workspace_1_1FloatSettingRow" ],
        [ "GroupVM", "classeditor_1_1Workspace_1_1GroupVM.html", null ],
        [ "HierarchyConnectorLayer", "classeditor_1_1Workspace_1_1HierarchyConnectorLayer.html", null ],
        [ "HierarchyElement", "classeditor_1_1Workspace_1_1HierarchyElement.html", null ],
        [ "HierarchyState", "classeditor_1_1Workspace_1_1HierarchyState.html", null ],
        [ "HierarchyView", "classeditor_1_1Workspace_1_1HierarchyView.html", null ],
        [ "HierarchyViewModel", "classeditor_1_1Workspace_1_1HierarchyViewModel.html", null ],
        [ "HistoryConflictDialogViewModel", "classeditor_1_1Workspace_1_1HistoryConflictDialogViewModel.html", null ],
        [ "HistoryConflictItemViewModel", "classeditor_1_1Workspace_1_1HistoryConflictItemViewModel.html", null ],
        [ "HistoryConflictWindow", "classeditor_1_1Workspace_1_1HistoryConflictWindow.html", null ],
        [ "HistoryGraphCell", "classeditor_1_1Workspace_1_1HistoryGraphCell.html", null ],
        [ "HistoryRowViewModel", "classeditor_1_1Workspace_1_1HistoryRowViewModel.html", null ],
        [ "HistoryView", "classeditor_1_1Workspace_1_1HistoryView.html", null ],
        [ "HistoryViewModel", "classeditor_1_1Workspace_1_1HistoryViewModel.html", null ],
        [ "IAutosavable", "interfaceeditor_1_1Workspace_1_1IAutosavable.html", null ],
        [ "InspectorState", "classeditor_1_1Workspace_1_1InspectorState.html", null ],
        [ "InspectorView", "classeditor_1_1Workspace_1_1InspectorView.html", null ],
        [ "InspectorViewModel", "classeditor_1_1Workspace_1_1InspectorViewModel.html", null ],
        [ "IntSettingRow", "classeditor_1_1Workspace_1_1IntSettingRow.html", null ],
        [ "LayoutFile", "classeditor_1_1Workspace_1_1LayoutFile.html", null ],
        [ "LayoutNode", "classeditor_1_1Workspace_1_1LayoutNode.html", null ],
        [ "LayoutWindowNode", "classeditor_1_1Workspace_1_1LayoutWindowNode.html", null ],
        [ "MainWindowView", "classeditor_1_1Workspace_1_1MainWindowView.html", null ],
        [ "MainWindowViewModel", "classeditor_1_1Workspace_1_1MainWindowViewModel.html", null ],
        [ "PlayWindow", "classeditor_1_1Workspace_1_1PlayWindow.html", null ],
        [ "ProjectSettingsView", "classeditor_1_1Workspace_1_1ProjectSettingsView.html", null ],
        [ "ProjectSettingsViewModel", "classeditor_1_1Workspace_1_1ProjectSettingsViewModel.html", null ],
        [ "ProjectSettingsWindow", "classeditor_1_1Workspace_1_1ProjectSettingsWindow.html", null ],
        [ "RendererSettingsView", "classeditor_1_1Workspace_1_1RendererSettingsView.html", null ],
        [ "RendererSettingsViewModel", "classeditor_1_1Workspace_1_1RendererSettingsViewModel.html", "classeditor_1_1Workspace_1_1RendererSettingsViewModel" ],
        [ "RenderPassVM", "classeditor_1_1Workspace_1_1RenderPassVM.html", null ],
        [ "SchemaEditorState", "classeditor_1_1Workspace_1_1SchemaEditorState.html", null ],
        [ "SettingCategory", "classeditor_1_1Workspace_1_1SettingCategory.html", null ],
        [ "SettingRow", "classeditor_1_1Workspace_1_1SettingRow.html", "classeditor_1_1Workspace_1_1SettingRow" ],
        [ "SettingsSection", "classeditor_1_1Workspace_1_1SettingsSection.html", null ],
        [ "SignalCardViewModel", "classeditor_1_1Workspace_1_1SignalCardViewModel.html", null ],
        [ "SignalConnectionDialogViewModel", "classeditor_1_1Workspace_1_1SignalConnectionDialogViewModel.html", null ],
        [ "SignalConnectionViewModel", "classeditor_1_1Workspace_1_1SignalConnectionViewModel.html", null ],
        [ "SignalConnectionWindow", "classeditor_1_1Workspace_1_1SignalConnectionWindow.html", null ],
        [ "SignalFunctionViewModel", "classeditor_1_1Workspace_1_1SignalFunctionViewModel.html", null ],
        [ "SignalItemViewModel", "classeditor_1_1Workspace_1_1SignalItemViewModel.html", null ],
        [ "SignalsView", "classeditor_1_1Workspace_1_1SignalsView.html", null ],
        [ "SignalsViewModel", "classeditor_1_1Workspace_1_1SignalsViewModel.html", null ],
        [ "StringSettingRow", "classeditor_1_1Workspace_1_1StringSettingRow.html", null ],
        [ "SubgroupVM", "classeditor_1_1Workspace_1_1SubgroupVM.html", null ],
        [ "ToastZoneFactory", "classeditor_1_1Workspace_1_1ToastZoneFactory.html", null ],
        [ "ViewportControl", "classeditor_1_1Workspace_1_1ViewportControl.html", null ],
        [ "WorkspaceHistoryRevision", "classeditor_1_1Workspace_1_1WorkspaceHistoryRevision.html", null ],
        [ "WorkspaceHistoryState", "classeditor_1_1Workspace_1_1WorkspaceHistoryState.html", null ],
        [ "WorkspaceView", "classeditor_1_1Workspace_1_1WorkspaceView.html", null ],
        [ "WorkspaceViewModel", "classeditor_1_1Workspace_1_1WorkspaceViewModel.html", null ]
      ] ],
      [ "App", "classeditor_1_1App.html", null ],
      [ "ViewLocator", "classeditor_1_1ViewLocator.html", null ],
      [ "ViewModelBase", "classeditor_1_1ViewModelBase.html", null ]
    ] ],
    [ "event", null, [
      [ "_detail", null, [
        [ "IEvent", "structevent_1_1__detail_1_1IEvent.html", null ],
        [ "ProtoAutoRegister", "structevent_1_1__detail_1_1ProtoAutoRegister.html", null ],
        [ "ProtoEntry", "structevent_1_1__detail_1_1ProtoEntry.html", "structevent_1_1__detail_1_1ProtoEntry" ]
      ] ],
      [ "AddSignalConnection", "structevent_1_1AddSignalConnection.html", null ],
      [ "AttachNode", "structevent_1_1AttachNode.html", null ],
      [ "CacheNode", "structevent_1_1CacheNode.html", null ],
      [ "CaptureFrame", "structevent_1_1CaptureFrame.html", null ],
      [ "ClearEditorSignalConnections", "structevent_1_1ClearEditorSignalConnections.html", null ],
      [ "ClearUnusedAssets", "structevent_1_1ClearUnusedAssets.html", null ],
      [ "ContactBegin", "structevent_1_1ContactBegin.html", null ],
      [ "ContactEnd", "structevent_1_1ContactEnd.html", null ],
      [ "ContactEventData", "structevent_1_1ContactEventData.html", null ],
      [ "ContactPersist", "structevent_1_1ContactPersist.html", null ],
      [ "DataAssetReloaded", "structevent_1_1DataAssetReloaded.html", null ],
      [ "DestroyNode", "structevent_1_1DestroyNode.html", null ],
      [ "EditorCameraFlyMode", "structevent_1_1EditorCameraFlyMode.html", null ],
      [ "EditorCameraGesture", "structevent_1_1EditorCameraGesture.html", null ],
      [ "EditorCameraLook", "structevent_1_1EditorCameraLook.html", null ],
      [ "EditorCameraMoveState", "structevent_1_1EditorCameraMoveState.html", null ],
      [ "Event", "structevent_1_1Event.html", "structevent_1_1Event" ],
      [ "EventSystem", "structevent_1_1EventSystem.html", "structevent_1_1EventSystem" ],
      [ "ExitApplication", "structevent_1_1ExitApplication.html", null ],
      [ "HistoryConflict", "structevent_1_1HistoryConflict.html", null ],
      [ "HistoryConflictResolution", "structevent_1_1HistoryConflictResolution.html", null ],
      [ "HistoryRevision", "structevent_1_1HistoryRevision.html", null ],
      [ "InputEvent", "structevent_1_1InputEvent.html", null ],
      [ "InspectorContent", "structevent_1_1InspectorContent.html", "structevent_1_1InspectorContent" ],
      [ "InspectorLuaContent", "structevent_1_1InspectorLuaContent.html", "structevent_1_1InspectorLuaContent" ],
      [ "LastInputType", "structevent_1_1LastInputType.html", null ],
      [ "Listener", "classevent_1_1Listener.html", "classevent_1_1Listener" ],
      [ "LoadNode", "structevent_1_1LoadNode.html", null ],
      [ "LoadNodeByURI", "structevent_1_1LoadNodeByURI.html", null ],
      [ "MakeNodeGlobal", "structevent_1_1MakeNodeGlobal.html", null ],
      [ "MaterialAssetReloaded", "structevent_1_1MaterialAssetReloaded.html", null ],
      [ "MusicBeat", "structevent_1_1MusicBeat.html", "structevent_1_1MusicBeat" ],
      [ "MusicMarker", "structevent_1_1MusicMarker.html", null ],
      [ "MusicStopped", "structevent_1_1MusicStopped.html", null ],
      [ "NodeCallFunction", "structevent_1_1NodeCallFunction.html", null ],
      [ "NodeChangeLuaParam", "structevent_1_1NodeChangeLuaParam.html", null ],
      [ "NodeChangeName", "structevent_1_1NodeChangeName.html", null ],
      [ "NodeChangeParam", "structevent_1_1NodeChangeParam.html", null ],
      [ "NodeChangeType", "structevent_1_1NodeChangeType.html", null ],
      [ "NodeEnabled", "structevent_1_1NodeEnabled.html", null ],
      [ "NodePicked", "structevent_1_1NodePicked.html", null ],
      [ "PlayHaptic", "structevent_1_1PlayHaptic.html", "structevent_1_1PlayHaptic" ],
      [ "PlayHapticDirect", "structevent_1_1PlayHapticDirect.html", "structevent_1_1PlayHapticDirect" ],
      [ "PrefabAssetReloaded", "structevent_1_1PrefabAssetReloaded.html", null ],
      [ "ProceduralVoxelLayout", "structevent_1_1ProceduralVoxelLayout.html", "structevent_1_1ProceduralVoxelLayout" ],
      [ "ProceduralVoxelPromoted", "structevent_1_1ProceduralVoxelPromoted.html", null ],
      [ "ProtoTraits", "structevent_1_1ProtoTraits.html", null ],
      [ "ProtoTraits&lt; AddSignalConnection &gt;", "structevent_1_1ProtoTraits_3_01AddSignalConnection_01_4.html", null ],
      [ "ProtoTraits&lt; CaptureFrame &gt;", "structevent_1_1ProtoTraits_3_01CaptureFrame_01_4.html", null ],
      [ "ProtoTraits&lt; ClearEditorSignalConnections &gt;", "structevent_1_1ProtoTraits_3_01ClearEditorSignalConnections_01_4.html", null ],
      [ "ProtoTraits&lt; EditorCameraFlyMode &gt;", "structevent_1_1ProtoTraits_3_01EditorCameraFlyMode_01_4.html", null ],
      [ "ProtoTraits&lt; EditorCameraGesture &gt;", "structevent_1_1ProtoTraits_3_01EditorCameraGesture_01_4.html", null ],
      [ "ProtoTraits&lt; EditorCameraLook &gt;", "structevent_1_1ProtoTraits_3_01EditorCameraLook_01_4.html", null ],
      [ "ProtoTraits&lt; EditorCameraMoveState &gt;", "structevent_1_1ProtoTraits_3_01EditorCameraMoveState_01_4.html", null ],
      [ "ProtoTraits&lt; ExitApplication &gt;", "structevent_1_1ProtoTraits_3_01ExitApplication_01_4.html", null ],
      [ "ProtoTraits&lt; HistoryConflict &gt;", "structevent_1_1ProtoTraits_3_01HistoryConflict_01_4.html", null ],
      [ "ProtoTraits&lt; HistoryConflictResolution &gt;", "structevent_1_1ProtoTraits_3_01HistoryConflictResolution_01_4.html", null ],
      [ "ProtoTraits&lt; HistoryRevision &gt;", "structevent_1_1ProtoTraits_3_01HistoryRevision_01_4.html", null ],
      [ "ProtoTraits&lt; InspectorContent &gt;", "structevent_1_1ProtoTraits_3_01InspectorContent_01_4.html", null ],
      [ "ProtoTraits&lt; InspectorContent::InspectorField &gt;", "structevent_1_1ProtoTraits_3_01InspectorContent_1_1InspectorField_01_4.html", null ],
      [ "ProtoTraits&lt; InspectorLuaContent &gt;", "structevent_1_1ProtoTraits_3_01InspectorLuaContent_01_4.html", null ],
      [ "ProtoTraits&lt; InspectorLuaContent::LuaField &gt;", "structevent_1_1ProtoTraits_3_01InspectorLuaContent_1_1LuaField_01_4.html", null ],
      [ "ProtoTraits&lt; InspectorLuaContent::LuaGroup &gt;", "structevent_1_1ProtoTraits_3_01InspectorLuaContent_1_1LuaGroup_01_4.html", null ],
      [ "ProtoTraits&lt; InspectorLuaContent::LuaScriptCard &gt;", "structevent_1_1ProtoTraits_3_01InspectorLuaContent_1_1LuaScriptCard_01_4.html", null ],
      [ "ProtoTraits&lt; InspectorLuaContent::LuaSubgroup &gt;", "structevent_1_1ProtoTraits_3_01InspectorLuaContent_1_1LuaSubgroup_01_4.html", null ],
      [ "ProtoTraits&lt; NodeCallFunction &gt;", "structevent_1_1ProtoTraits_3_01NodeCallFunction_01_4.html", null ],
      [ "ProtoTraits&lt; NodeChangeLuaParam &gt;", "structevent_1_1ProtoTraits_3_01NodeChangeLuaParam_01_4.html", null ],
      [ "ProtoTraits&lt; NodeChangeName &gt;", "structevent_1_1ProtoTraits_3_01NodeChangeName_01_4.html", null ],
      [ "ProtoTraits&lt; NodeChangeParam &gt;", "structevent_1_1ProtoTraits_3_01NodeChangeParam_01_4.html", null ],
      [ "ProtoTraits&lt; NodeChangeType &gt;", "structevent_1_1ProtoTraits_3_01NodeChangeType_01_4.html", null ],
      [ "ProtoTraits&lt; NodeEnabled &gt;", "structevent_1_1ProtoTraits_3_01NodeEnabled_01_4.html", null ],
      [ "ProtoTraits&lt; NodePicked &gt;", "structevent_1_1ProtoTraits_3_01NodePicked_01_4.html", null ],
      [ "ProtoTraits&lt; ProceduralVoxelLayout &gt;", "structevent_1_1ProtoTraits_3_01ProceduralVoxelLayout_01_4.html", null ],
      [ "ProtoTraits&lt; ProceduralVoxelPromoted &gt;", "structevent_1_1ProtoTraits_3_01ProceduralVoxelPromoted_01_4.html", null ],
      [ "ProtoTraits&lt; ReloadAssetsManifest &gt;", "structevent_1_1ProtoTraits_3_01ReloadAssetsManifest_01_4.html", null ],
      [ "ProtoTraits&lt; RemoveSignalConnection &gt;", "structevent_1_1ProtoTraits_3_01RemoveSignalConnection_01_4.html", null ],
      [ "ProtoTraits&lt; RenderPassList &gt;", "structevent_1_1ProtoTraits_3_01RenderPassList_01_4.html", null ],
      [ "ProtoTraits&lt; RequestHierarchyUpdate &gt;", "structevent_1_1ProtoTraits_3_01RequestHierarchyUpdate_01_4.html", null ],
      [ "ProtoTraits&lt; RequestRenderPasses &gt;", "structevent_1_1ProtoTraits_3_01RequestRenderPasses_01_4.html", null ],
      [ "ProtoTraits&lt; RequestShaderReflection &gt;", "structevent_1_1ProtoTraits_3_01RequestShaderReflection_01_4.html", null ],
      [ "ProtoTraits&lt; RequestSignalCallables &gt;", "structevent_1_1ProtoTraits_3_01RequestSignalCallables_01_4.html", null ],
      [ "ProtoTraits&lt; RequestSignalState &gt;", "structevent_1_1ProtoTraits_3_01RequestSignalState_01_4.html", null ],
      [ "ProtoTraits&lt; SetActiveWorkspace &gt;", "structevent_1_1ProtoTraits_3_01SetActiveWorkspace_01_4.html", null ],
      [ "ProtoTraits&lt; SetCameraMode &gt;", "structevent_1_1ProtoTraits_3_01SetCameraMode_01_4.html", null ],
      [ "ProtoTraits&lt; SetCoordinateSpace &gt;", "structevent_1_1ProtoTraits_3_01SetCoordinateSpace_01_4.html", null ],
      [ "ProtoTraits&lt; SetEditorCameraSettings &gt;", "structevent_1_1ProtoTraits_3_01SetEditorCameraSettings_01_4.html", null ],
      [ "ProtoTraits&lt; SetFocusedNode &gt;", "structevent_1_1ProtoTraits_3_01SetFocusedNode_01_4.html", null ],
      [ "ProtoTraits&lt; SetGizmoTool &gt;", "structevent_1_1ProtoTraits_3_01SetGizmoTool_01_4.html", null ],
      [ "ProtoTraits&lt; SetRenderMode &gt;", "structevent_1_1ProtoTraits_3_01SetRenderMode_01_4.html", null ],
      [ "ProtoTraits&lt; SetRenderPassEnabled &gt;", "structevent_1_1ProtoTraits_3_01SetRenderPassEnabled_01_4.html", null ],
      [ "ProtoTraits&lt; SetShowOthers &gt;", "structevent_1_1ProtoTraits_3_01SetShowOthers_01_4.html", null ],
      [ "ProtoTraits&lt; SetSnapping &gt;", "structevent_1_1ProtoTraits_3_01SetSnapping_01_4.html", null ],
      [ "ProtoTraits&lt; SetVoxelCutPreview &gt;", "structevent_1_1ProtoTraits_3_01SetVoxelCutPreview_01_4.html", null ],
      [ "ProtoTraits&lt; SetVoxelEditorOverlays &gt;", "structevent_1_1ProtoTraits_3_01SetVoxelEditorOverlays_01_4.html", null ],
      [ "ProtoTraits&lt; SetVoxelTool &gt;", "structevent_1_1ProtoTraits_3_01SetVoxelTool_01_4.html", null ],
      [ "ProtoTraits&lt; ShaderRecompiled &gt;", "structevent_1_1ProtoTraits_3_01ShaderRecompiled_01_4.html", null ],
      [ "ProtoTraits&lt; ShaderReflectionReady &gt;", "structevent_1_1ProtoTraits_3_01ShaderReflectionReady_01_4.html", null ],
      [ "ProtoTraits&lt; SignalCallables &gt;", "structevent_1_1ProtoTraits_3_01SignalCallables_01_4.html", null ],
      [ "ProtoTraits&lt; SignalState &gt;", "structevent_1_1ProtoTraits_3_01SignalState_01_4.html", null ],
      [ "ProtoTraits&lt; UpdateHierarchyData &gt;", "structevent_1_1ProtoTraits_3_01UpdateHierarchyData_01_4.html", null ],
      [ "ProtoTraits&lt; UpdateHierarchyData::HierarchyElement &gt;", "structevent_1_1ProtoTraits_3_01UpdateHierarchyData_1_1HierarchyElement_01_4.html", null ],
      [ "ProtoTraits&lt; UpdateWorkspaceHistory &gt;", "structevent_1_1ProtoTraits_3_01UpdateWorkspaceHistory_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelBake &gt;", "structevent_1_1ProtoTraits_3_01VoxelBake_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelBakeCompleted &gt;", "structevent_1_1ProtoTraits_3_01VoxelBakeCompleted_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelBucketFill &gt;", "structevent_1_1ProtoTraits_3_01VoxelBucketFill_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelCollapsePieces &gt;", "structevent_1_1ProtoTraits_3_01VoxelCollapsePieces_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelCreatePiece &gt;", "structevent_1_1ProtoTraits_3_01VoxelCreatePiece_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelExtrude &gt;", "structevent_1_1ProtoTraits_3_01VoxelExtrude_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelRotatePieces &gt;", "structevent_1_1ProtoTraits_3_01VoxelRotatePieces_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelSetPieceBounds &gt;", "structevent_1_1ProtoTraits_3_01VoxelSetPieceBounds_01_4.html", null ],
      [ "ProtoTraits&lt; VoxelSplitPieces &gt;", "structevent_1_1ProtoTraits_3_01VoxelSplitPieces_01_4.html", null ],
      [ "ProtoTraits&lt; WindowChar &gt;", "structevent_1_1ProtoTraits_3_01WindowChar_01_4.html", null ],
      [ "ProtoTraits&lt; WindowClose &gt;", "structevent_1_1ProtoTraits_3_01WindowClose_01_4.html", null ],
      [ "ProtoTraits&lt; WindowDisplayScale &gt;", "structevent_1_1ProtoTraits_3_01WindowDisplayScale_01_4.html", null ],
      [ "ProtoTraits&lt; WindowDrop &gt;", "structevent_1_1ProtoTraits_3_01WindowDrop_01_4.html", null ],
      [ "ProtoTraits&lt; WindowKey &gt;", "structevent_1_1ProtoTraits_3_01WindowKey_01_4.html", null ],
      [ "ProtoTraits&lt; WindowMouseButton &gt;", "structevent_1_1ProtoTraits_3_01WindowMouseButton_01_4.html", null ],
      [ "ProtoTraits&lt; WindowMouseLock &gt;", "structevent_1_1ProtoTraits_3_01WindowMouseLock_01_4.html", null ],
      [ "ProtoTraits&lt; WindowMousePosition &gt;", "structevent_1_1ProtoTraits_3_01WindowMousePosition_01_4.html", null ],
      [ "ProtoTraits&lt; WindowMouseScroll &gt;", "structevent_1_1ProtoTraits_3_01WindowMouseScroll_01_4.html", null ],
      [ "ProtoTraits&lt; WindowResize &gt;", "structevent_1_1ProtoTraits_3_01WindowResize_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceApplyHistorySnapshot &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceApplyHistorySnapshot_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceAutosave &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceAutosave_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceConvertToProceduralVoxel &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceConvertToProceduralVoxel_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceCopyNode &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceCopyNode_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceCreate &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceCreate_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceCreateNode &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceCreateNode_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceDestroy &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceDestroy_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceDuplicateNode &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceDuplicateNode_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceHistoryCommitted &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceHistoryCommitted_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceHistoryConflicts &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceHistoryConflicts_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceHistoryInitialSnapshot &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceHistoryInitialSnapshot_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceHistoryMergePrepared &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceHistoryMergePrepared_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceHistorySnapshotApplied &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceHistorySnapshotApplied_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceHistoryTransaction &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceHistoryTransaction_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceMoveNodeTo &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceMoveNodeTo_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspacePasteNode &gt;", "structevent_1_1ProtoTraits_3_01WorkspacePasteNode_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspacePause &gt;", "structevent_1_1ProtoTraits_3_01WorkspacePause_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspacePrepareHistoryMerge &gt;", "structevent_1_1ProtoTraits_3_01WorkspacePrepareHistoryMerge_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspacePromoteNode &gt;", "structevent_1_1ProtoTraits_3_01WorkspacePromoteNode_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceRemoveNode &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceRemoveNode_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceResolveHistoryConflicts &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceResolveHistoryConflicts_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceSave &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceSave_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceSaveCompleted &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceSaveCompleted_01_4.html", null ],
      [ "ProtoTraits&lt; WorkspaceSpawn &gt;", "structevent_1_1ProtoTraits_3_01WorkspaceSpawn_01_4.html", null ],
      [ "ReloadAssetsManifest", "structevent_1_1ReloadAssetsManifest.html", null ],
      [ "ReloadInputActions", "structevent_1_1ReloadInputActions.html", null ],
      [ "RemoveSignalConnection", "structevent_1_1RemoveSignalConnection.html", null ],
      [ "RenderPassList", "structevent_1_1RenderPassList.html", "structevent_1_1RenderPassList" ],
      [ "RequestHierarchyUpdate", "structevent_1_1RequestHierarchyUpdate.html", null ],
      [ "RequestRenderPasses", "structevent_1_1RequestRenderPasses.html", null ],
      [ "RequestShaderReflection", "structevent_1_1RequestShaderReflection.html", null ],
      [ "RequestSignalCallables", "structevent_1_1RequestSignalCallables.html", null ],
      [ "RequestSignalState", "structevent_1_1RequestSignalState.html", null ],
      [ "RequestWorkspaceHistory", "structevent_1_1RequestWorkspaceHistory.html", null ],
      [ "ScriptAssetReloaded", "structevent_1_1ScriptAssetReloaded.html", null ],
      [ "SetActiveCamera", "structevent_1_1SetActiveCamera.html", null ],
      [ "SetActiveWorkspace", "structevent_1_1SetActiveWorkspace.html", null ],
      [ "SetCameraMode", "structevent_1_1SetCameraMode.html", null ],
      [ "SetCoordinateSpace", "structevent_1_1SetCoordinateSpace.html", null ],
      [ "SetEditorCameraSettings", "structevent_1_1SetEditorCameraSettings.html", null ],
      [ "SetFocusedNode", "structevent_1_1SetFocusedNode.html", null ],
      [ "SetGizmoTool", "structevent_1_1SetGizmoTool.html", null ],
      [ "SetHapticsMultiplier", "structevent_1_1SetHapticsMultiplier.html", null ],
      [ "SetInputLayer", "structevent_1_1SetInputLayer.html", null ],
      [ "SetInputLayout", "structevent_1_1SetInputLayout.html", null ],
      [ "SetRenderMode", "structevent_1_1SetRenderMode.html", null ],
      [ "SetRenderPassEnabled", "structevent_1_1SetRenderPassEnabled.html", null ],
      [ "SetShowOthers", "structevent_1_1SetShowOthers.html", null ],
      [ "SetSnapping", "structevent_1_1SetSnapping.html", null ],
      [ "SetVoxelCutPreview", "structevent_1_1SetVoxelCutPreview.html", null ],
      [ "SetVoxelEditorOverlays", "structevent_1_1SetVoxelEditorOverlays.html", null ],
      [ "SetVoxelTool", "structevent_1_1SetVoxelTool.html", null ],
      [ "SetWorldRoot", "structevent_1_1SetWorldRoot.html", null ],
      [ "ShaderAssetReloaded", "structevent_1_1ShaderAssetReloaded.html", null ],
      [ "ShaderRecompiled", "structevent_1_1ShaderRecompiled.html", null ],
      [ "ShaderReflectionReady", "structevent_1_1ShaderReflectionReady.html", null ],
      [ "SignalCallable", "structevent_1_1SignalCallable.html", null ],
      [ "SignalCallables", "structevent_1_1SignalCallables.html", null ],
      [ "SignalConnection", "structevent_1_1SignalConnection.html", null ],
      [ "SignalParameter", "structevent_1_1SignalParameter.html", null ],
      [ "SignalState", "structevent_1_1SignalState.html", null ],
      [ "SignalStateEntry", "structevent_1_1SignalStateEntry.html", null ],
      [ "ThreadListener", "classevent_1_1ThreadListener.html", "classevent_1_1ThreadListener" ],
      [ "UIAssetReloaded", "structevent_1_1UIAssetReloaded.html", null ],
      [ "UpdateHierarchyData", "structevent_1_1UpdateHierarchyData.html", "structevent_1_1UpdateHierarchyData" ],
      [ "UpdateWorkspaceHistory", "structevent_1_1UpdateWorkspaceHistory.html", null ],
      [ "VoxelBake", "structevent_1_1VoxelBake.html", null ],
      [ "VoxelBakeCompleted", "structevent_1_1VoxelBakeCompleted.html", null ],
      [ "VoxelBucketFill", "structevent_1_1VoxelBucketFill.html", null ],
      [ "VoxelCollapsePieces", "structevent_1_1VoxelCollapsePieces.html", null ],
      [ "VoxelCreatePiece", "structevent_1_1VoxelCreatePiece.html", null ],
      [ "VoxelExtrude", "structevent_1_1VoxelExtrude.html", null ],
      [ "VoxelPaletteAssetReloaded", "structevent_1_1VoxelPaletteAssetReloaded.html", null ],
      [ "VoxelPieceLayoutData", "structevent_1_1VoxelPieceLayoutData.html", null ],
      [ "VoxelProjectionData", "structevent_1_1VoxelProjectionData.html", "structevent_1_1VoxelProjectionData" ],
      [ "VoxelRotatePieces", "structevent_1_1VoxelRotatePieces.html", null ],
      [ "VoxelSetPieceBounds", "structevent_1_1VoxelSetPieceBounds.html", null ],
      [ "VoxelSplitPieces", "structevent_1_1VoxelSplitPieces.html", null ],
      [ "WindowChar", "structevent_1_1WindowChar.html", null ],
      [ "WindowClose", "structevent_1_1WindowClose.html", null ],
      [ "WindowDisplayScale", "structevent_1_1WindowDisplayScale.html", null ],
      [ "WindowDrop", "structevent_1_1WindowDrop.html", "structevent_1_1WindowDrop" ],
      [ "WindowFocus", "structevent_1_1WindowFocus.html", null ],
      [ "WindowKey", "structevent_1_1WindowKey.html", "structevent_1_1WindowKey" ],
      [ "WindowMouseButton", "structevent_1_1WindowMouseButton.html", null ],
      [ "WindowMouseLock", "structevent_1_1WindowMouseLock.html", null ],
      [ "WindowMousePosition", "structevent_1_1WindowMousePosition.html", null ],
      [ "WindowMouseScroll", "structevent_1_1WindowMouseScroll.html", null ],
      [ "WindowResize", "structevent_1_1WindowResize.html", null ],
      [ "WorkspaceApplyHistorySnapshot", "structevent_1_1WorkspaceApplyHistorySnapshot.html", null ],
      [ "WorkspaceAutosave", "structevent_1_1WorkspaceAutosave.html", null ],
      [ "WorkspaceCheckoutHistory", "structevent_1_1WorkspaceCheckoutHistory.html", null ],
      [ "WorkspaceCherryPickHistory", "structevent_1_1WorkspaceCherryPickHistory.html", null ],
      [ "WorkspaceConvertToProceduralVoxel", "structevent_1_1WorkspaceConvertToProceduralVoxel.html", null ],
      [ "WorkspaceCopyNode", "structevent_1_1WorkspaceCopyNode.html", null ],
      [ "WorkspaceCreate", "structevent_1_1WorkspaceCreate.html", null ],
      [ "WorkspaceCreateNode", "structevent_1_1WorkspaceCreateNode.html", null ],
      [ "WorkspaceDestroy", "structevent_1_1WorkspaceDestroy.html", null ],
      [ "WorkspaceDuplicateNode", "structevent_1_1WorkspaceDuplicateNode.html", null ],
      [ "WorkspaceHistoryCommitted", "structevent_1_1WorkspaceHistoryCommitted.html", null ],
      [ "WorkspaceHistoryConflicts", "structevent_1_1WorkspaceHistoryConflicts.html", null ],
      [ "WorkspaceHistoryInitialSnapshot", "structevent_1_1WorkspaceHistoryInitialSnapshot.html", null ],
      [ "WorkspaceHistoryMergePrepared", "structevent_1_1WorkspaceHistoryMergePrepared.html", null ],
      [ "WorkspaceHistorySnapshotApplied", "structevent_1_1WorkspaceHistorySnapshotApplied.html", null ],
      [ "WorkspaceHistoryTransaction", "structevent_1_1WorkspaceHistoryTransaction.html", null ],
      [ "WorkspaceMergeHistory", "structevent_1_1WorkspaceMergeHistory.html", null ],
      [ "WorkspaceMoveNodeTo", "structevent_1_1WorkspaceMoveNodeTo.html", null ],
      [ "WorkspacePasteNode", "structevent_1_1WorkspacePasteNode.html", null ],
      [ "WorkspacePause", "structevent_1_1WorkspacePause.html", null ],
      [ "WorkspacePrepareHistoryMerge", "structevent_1_1WorkspacePrepareHistoryMerge.html", null ],
      [ "WorkspacePromoteNode", "structevent_1_1WorkspacePromoteNode.html", null ],
      [ "WorkspaceRedo", "structevent_1_1WorkspaceRedo.html", null ],
      [ "WorkspaceRemove", "structevent_1_1WorkspaceRemove.html", null ],
      [ "WorkspaceRemoveNode", "structevent_1_1WorkspaceRemoveNode.html", null ],
      [ "WorkspaceResolveHistoryConflicts", "structevent_1_1WorkspaceResolveHistoryConflicts.html", null ],
      [ "WorkspaceSave", "structevent_1_1WorkspaceSave.html", null ],
      [ "WorkspaceSaveCompleted", "structevent_1_1WorkspaceSaveCompleted.html", null ],
      [ "WorkspaceSpawn", "structevent_1_1WorkspaceSpawn.html", null ],
      [ "WorkspaceUndo", "structevent_1_1WorkspaceUndo.html", null ]
    ] ],
    [ "input", null, [
      [ "Action", "classinput_1_1Action.html", "classinput_1_1Action" ],
      [ "Axis1DTrigger", "classinput_1_1Axis1DTrigger.html", "classinput_1_1Axis1DTrigger" ],
      [ "Axis2DTrigger", "classinput_1_1Axis2DTrigger.html", "classinput_1_1Axis2DTrigger" ],
      [ "Bind", "classinput_1_1Bind.html", "classinput_1_1Bind" ],
      [ "CursorTrigger", "classinput_1_1CursorTrigger.html", "classinput_1_1CursorTrigger" ],
      [ "DeadzoneModifier", "classinput_1_1DeadzoneModifier.html", "classinput_1_1DeadzoneModifier" ],
      [ "EvalContext", "structinput_1_1EvalContext.html", "structinput_1_1EvalContext" ],
      [ "ExponentialModifier", "classinput_1_1ExponentialModifier.html", "classinput_1_1ExponentialModifier" ],
      [ "HapticsSystem", "classinput_1_1HapticsSystem.html", "classinput_1_1HapticsSystem" ],
      [ "HoldTrigger", "classinput_1_1HoldTrigger.html", "classinput_1_1HoldTrigger" ],
      [ "IController", "classinput_1_1IController.html", null ],
      [ "IModifier", "classinput_1_1IModifier.html", "classinput_1_1IModifier" ],
      [ "InputSample", "structinput_1_1InputSample.html", null ],
      [ "InputSystem", "classinput_1_1InputSystem.html", "classinput_1_1InputSystem" ],
      [ "InvertModifier", "classinput_1_1InvertModifier.html", "classinput_1_1InvertModifier" ],
      [ "ITrigger", "classinput_1_1ITrigger.html", "classinput_1_1ITrigger" ],
      [ "KeyCode", "structinput_1_1KeyCode.html", null ],
      [ "KeyModifier", "classinput_1_1KeyModifier.html", "classinput_1_1KeyModifier" ],
      [ "PlayerController", "classinput_1_1PlayerController.html", "classinput_1_1PlayerController" ],
      [ "PulseTrigger", "classinput_1_1PulseTrigger.html", "classinput_1_1PulseTrigger" ],
      [ "ReleaseTrigger", "classinput_1_1ReleaseTrigger.html", "classinput_1_1ReleaseTrigger" ],
      [ "ScaleByDeltaTimeModifier", "classinput_1_1ScaleByDeltaTimeModifier.html", "classinput_1_1ScaleByDeltaTimeModifier" ],
      [ "ScaleModifier", "classinput_1_1ScaleModifier.html", "classinput_1_1ScaleModifier" ],
      [ "SignalList", "structinput_1_1SignalList.html", "structinput_1_1SignalList" ],
      [ "SmoothModifier", "classinput_1_1SmoothModifier.html", "classinput_1_1SmoothModifier" ],
      [ "StartTrigger", "classinput_1_1StartTrigger.html", "classinput_1_1StartTrigger" ],
      [ "Value", "structinput_1_1Value.html", "structinput_1_1Value" ]
    ] ],
    [ "logging", null, [
      [ "Logger", "classlogging_1_1Logger.html", "classlogging_1_1Logger" ]
    ] ],
    [ "physics", null, [
      [ "_detail", null, [
        [ "BoxClipVertex", "structphysics_1_1__detail_1_1BoxClipVertex.html", null ],
        [ "BoxFeature", "structphysics_1_1__detail_1_1BoxFeature.html", null ],
        [ "BoxSatContacts", "structphysics_1_1__detail_1_1BoxSatContacts.html", null ],
        [ "BoxSatResult", "structphysics_1_1__detail_1_1BoxSatResult.html", null ],
        [ "BoxSupportEdge", "structphysics_1_1__detail_1_1BoxSupportEdge.html", null ],
        [ "BoxSupportPoint", "structphysics_1_1__detail_1_1BoxSupportPoint.html", null ],
        [ "ContactCandidate", "structphysics_1_1__detail_1_1ContactCandidate.html", null ],
        [ "FixedBuffer", "classphysics_1_1__detail_1_1FixedBuffer.html", null ],
        [ "SegmentBoxClosestPoints", "structphysics_1_1__detail_1_1SegmentBoxClosestPoints.html", null ],
        [ "SegmentClosestPoint", "structphysics_1_1__detail_1_1SegmentClosestPoint.html", null ],
        [ "SegmentClosestPoints", "structphysics_1_1__detail_1_1SegmentClosestPoints.html", null ],
        [ "WorldBox", "structphysics_1_1__detail_1_1WorldBox.html", null ],
        [ "WorldCapsule", "structphysics_1_1__detail_1_1WorldCapsule.html", null ],
        [ "WorldSphere", "structphysics_1_1__detail_1_1WorldSphere.html", null ]
      ] ],
      [ "AABB", "structphysics_1_1AABB.html", "structphysics_1_1AABB" ],
      [ "AABBTree", "classphysics_1_1AABBTree.html", null ],
      [ "AABBTreeDebugNode", "structphysics_1_1AABBTreeDebugNode.html", null ],
      [ "Accumulator", "classphysics_1_1Accumulator.html", null ],
      [ "Body", "structphysics_1_1Body.html", "structphysics_1_1Body" ],
      [ "BodyDescriptor", "structphysics_1_1BodyDescriptor.html", null ],
      [ "BodyID", "structphysics_1_1BodyID.html", null ],
      [ "BodyShapeKey", "structphysics_1_1BodyShapeKey.html", null ],
      [ "BodySlot", "structphysics_1_1BodySlot.html", null ],
      [ "BodyState", "structphysics_1_1BodyState.html", null ],
      [ "BoxCollider", "classphysics_1_1BoxCollider.html", null ],
      [ "BoxShape", "structphysics_1_1BoxShape.html", null ],
      [ "BoxVoxelPairView", "structphysics_1_1BoxVoxelPairView.html", null ],
      [ "BoxVoxelSplitInfo", "structphysics_1_1BoxVoxelSplitInfo.html", "structphysics_1_1BoxVoxelSplitInfo" ],
      [ "BroadPhase", "classphysics_1_1BroadPhase.html", null ],
      [ "BroadPhasePair", "structphysics_1_1BroadPhasePair.html", null ],
      [ "BroadPhaseStats", "structphysics_1_1BroadPhaseStats.html", null ],
      [ "CachedContact", "structphysics_1_1CachedContact.html", null ],
      [ "CachedManifold", "structphysics_1_1CachedManifold.html", "structphysics_1_1CachedManifold" ],
      [ "CapsuleCollider", "classphysics_1_1CapsuleCollider.html", null ],
      [ "CapsuleShape", "structphysics_1_1CapsuleShape.html", null ],
      [ "Collider", "classphysics_1_1Collider.html", null ],
      [ "CollisionElement", "structphysics_1_1CollisionElement.html", null ],
      [ "CollisionWorldView", "structphysics_1_1CollisionWorldView.html", null ],
      [ "Constraint", "structphysics_1_1Constraint.html", null ],
      [ "ContactFeatureID", "structphysics_1_1ContactFeatureID.html", null ],
      [ "ContactMaterial", "structphysics_1_1ContactMaterial.html", null ],
      [ "ContactPoint", "structphysics_1_1ContactPoint.html", null ],
      [ "DamageCommand", "structphysics_1_1DamageCommand.html", null ],
      [ "DetachedComponent", "structphysics_1_1DetachedComponent.html", null ],
      [ "DynamicRigidbody", "classphysics_1_1DynamicRigidbody.html", null ],
      [ "ExtractedFragment", "structphysics_1_1ExtractedFragment.html", "structphysics_1_1ExtractedFragment" ],
      [ "KinematicRigidbody", "classphysics_1_1KinematicRigidbody.html", null ],
      [ "Manifold", "structphysics_1_1Manifold.html", null ],
      [ "ManifoldQueue", "structphysics_1_1ManifoldQueue.html", null ],
      [ "Meta", "structphysics_1_1Meta.html", "structphysics_1_1Meta" ],
      [ "NarrowPhase", "classphysics_1_1NarrowPhase.html", "classphysics_1_1NarrowPhase" ],
      [ "PhysicsMaterial", "structphysics_1_1PhysicsMaterial.html", null ],
      [ "QueryContact", "structphysics_1_1QueryContact.html", null ],
      [ "RayHit", "structphysics_1_1RayHit.html", null ],
      [ "RemovedVoxels", "structphysics_1_1RemovedVoxels.html", "structphysics_1_1RemovedVoxels" ],
      [ "Rigidbody", "classphysics_1_1Rigidbody.html", null ],
      [ "Shape", "structphysics_1_1Shape.html", null ],
      [ "ShapeBoundsUpdate", "structphysics_1_1ShapeBoundsUpdate.html", null ],
      [ "ShapeID", "structphysics_1_1ShapeID.html", null ],
      [ "ShapeSlot", "structphysics_1_1ShapeSlot.html", null ],
      [ "Simulator", "classphysics_1_1Simulator.html", "classphysics_1_1Simulator" ],
      [ "SphereCollider", "classphysics_1_1SphereCollider.html", null ],
      [ "SphereShape", "structphysics_1_1SphereShape.html", null ],
      [ "StaticRigidbody", "classphysics_1_1StaticRigidbody.html", null ],
      [ "StepResult", "structphysics_1_1StepResult.html", "structphysics_1_1StepResult" ],
      [ "SweepHit", "structphysics_1_1SweepHit.html", null ],
      [ "TreeNode", "structphysics_1_1TreeNode.html", null ],
      [ "Tunables", "structphysics_1_1Tunables.html", "structphysics_1_1Tunables" ],
      [ "VoxelCandidate", "structphysics_1_1VoxelCandidate.html", null ],
      [ "VoxelDataID", "structphysics_1_1VoxelDataID.html", null ],
      [ "VoxelFeaturePayload", "structphysics_1_1VoxelFeaturePayload.html", null ],
      [ "VoxelPairPartial", "structphysics_1_1VoxelPairPartial.html", null ],
      [ "VoxelQueryContext", "structphysics_1_1VoxelQueryContext.html", null ],
      [ "VoxelRenderRecord", "structphysics_1_1VoxelRenderRecord.html", null ],
      [ "VoxelShape", "structphysics_1_1VoxelShape.html", null ],
      [ "VoxelShapeData", "structphysics_1_1VoxelShapeData.html", "structphysics_1_1VoxelShapeData" ],
      [ "VoxelShapeSlot", "structphysics_1_1VoxelShapeSlot.html", null ],
      [ "VoxelVoxelPairView", "structphysics_1_1VoxelVoxelPairView.html", null ],
      [ "VoxelVoxelSplitInfo", "structphysics_1_1VoxelVoxelSplitInfo.html", "structphysics_1_1VoxelVoxelSplitInfo" ]
    ] ],
    [ "renderer", null, [
      [ "light_culling", null, [
        [ "Sphere", "structrenderer_1_1light__culling_1_1Sphere.html", null ],
        [ "DepthRange", "structrenderer_1_1light__culling_1_1DepthRange.html", null ]
      ] ],
      [ "shadow_slots", null, [
        [ "Candidate", "structrenderer_1_1shadow__slots_1_1Candidate.html", null ],
        [ "Slot", "structrenderer_1_1shadow__slots_1_1Slot.html", null ]
      ] ],
      [ "voxel_debug", null, [
        [ "Rgb", "structrenderer_1_1voxel__debug_1_1Rgb.html", null ],
        [ "Probe", "structrenderer_1_1voxel__debug_1_1Probe.html", "structrenderer_1_1voxel__debug_1_1Probe" ],
        [ "MissProbe", "structrenderer_1_1voxel__debug_1_1MissProbe.html", null ],
        [ "ProbeResult", "structrenderer_1_1voxel__debug_1_1ProbeResult.html", null ],
        [ "Monitor", "classrenderer_1_1voxel__debug_1_1Monitor.html", "classrenderer_1_1voxel__debug_1_1Monitor" ]
      ] ],
      [ "BloomPass", "classrenderer_1_1BloomPass.html", "classrenderer_1_1BloomPass" ],
      [ "Box", "structrenderer_1_1Box.html", null ],
      [ "ClusterLightingPass", "classrenderer_1_1ClusterLightingPass.html", "classrenderer_1_1ClusterLightingPass" ],
      [ "CompiledShaderCode", "structrenderer_1_1CompiledShaderCode.html", null ],
      [ "CubeFaceBasis", "structrenderer_1_1CubeFaceBasis.html", null ],
      [ "CubemapTarget", "classrenderer_1_1CubemapTarget.html", null ],
      [ "DataValue", "classrenderer_1_1DataValue.html", "classrenderer_1_1DataValue" ],
      [ "DebugPass", "classrenderer_1_1DebugPass.html", "classrenderer_1_1DebugPass" ],
      [ "DepthPrepass", "classrenderer_1_1DepthPrepass.html", "classrenderer_1_1DepthPrepass" ],
      [ "DescriptorWriter", "classrenderer_1_1DescriptorWriter.html", null ],
      [ "DeviceScore", "structrenderer_1_1DeviceScore.html", null ],
      [ "EditorOverlays", "structrenderer_1_1EditorOverlays.html", "structrenderer_1_1EditorOverlays" ],
      [ "EnvironmentPass", "classrenderer_1_1EnvironmentPass.html", "classrenderer_1_1EnvironmentPass" ],
      [ "FxaaPass", "classrenderer_1_1FxaaPass.html", "classrenderer_1_1FxaaPass" ],
      [ "GpuScope", "classrenderer_1_1GpuScope.html", null ],
      [ "GpuTimer", "classrenderer_1_1GpuTimer.html", "classrenderer_1_1GpuTimer" ],
      [ "GridPass", "classrenderer_1_1GridPass.html", null ],
      [ "IOutputTarget", "classrenderer_1_1IOutputTarget.html", null ],
      [ "IPostProcessPass", "classrenderer_1_1IPostProcessPass.html", "classrenderer_1_1IPostProcessPass" ],
      [ "IVulkanResource", "classrenderer_1_1IVulkanResource.html", null ],
      [ "MaterialPass", "classrenderer_1_1MaterialPass.html", null ],
      [ "MaterialRuntime", "classrenderer_1_1MaterialRuntime.html", "classrenderer_1_1MaterialRuntime" ],
      [ "MeshUpload", "classrenderer_1_1MeshUpload.html", null ],
      [ "Meta", "structrenderer_1_1Meta.html", "structrenderer_1_1Meta" ],
      [ "PendingResourceUpload", "classrenderer_1_1PendingResourceUpload.html", "classrenderer_1_1PendingResourceUpload" ],
      [ "PostProcessSettings", "structrenderer_1_1PostProcessSettings.html", "structrenderer_1_1PostProcessSettings" ],
      [ "PostProcessTarget", "classrenderer_1_1PostProcessTarget.html", null ],
      [ "RawTextureUpload", "classrenderer_1_1RawTextureUpload.html", null ],
      [ "RayTracingScene", "classrenderer_1_1RayTracingScene.html", "classrenderer_1_1RayTracingScene" ],
      [ "ReflectionProbePass", "classrenderer_1_1ReflectionProbePass.html", "classrenderer_1_1ReflectionProbePass" ],
      [ "SceneDescriptorSets", "classrenderer_1_1SceneDescriptorSets.html", "classrenderer_1_1SceneDescriptorSets" ],
      [ "SDLOutputTarget", "classrenderer_1_1SDLOutputTarget.html", null ],
      [ "ShaderBinding", "structrenderer_1_1ShaderBinding.html", null ],
      [ "ShaderBlockMember", "structrenderer_1_1ShaderBlockMember.html", null ],
      [ "ShaderCache", "classrenderer_1_1ShaderCache.html", "classrenderer_1_1ShaderCache" ],
      [ "ShaderCompiler", "classrenderer_1_1ShaderCompiler.html", null ],
      [ "ShaderEntryPoint", "structrenderer_1_1ShaderEntryPoint.html", null ],
      [ "ShaderInspectorMeta", "structrenderer_1_1ShaderInspectorMeta.html", null ],
      [ "ShaderLayout", "classrenderer_1_1ShaderLayout.html", null ],
      [ "ShaderPushConstants", "structrenderer_1_1ShaderPushConstants.html", null ],
      [ "ShaderReflection", "structrenderer_1_1ShaderReflection.html", null ],
      [ "ShadowPass", "classrenderer_1_1ShadowPass.html", "classrenderer_1_1ShadowPass" ],
      [ "SharedTextureOutputTarget", "classrenderer_1_1SharedTextureOutputTarget.html", "classrenderer_1_1SharedTextureOutputTarget" ],
      [ "ShGridKey", "structrenderer_1_1ShGridKey.html", null ],
      [ "SkinnedBlasPool", "classrenderer_1_1SkinnedBlasPool.html", null ],
      [ "SkinningPass", "classrenderer_1_1SkinningPass.html", null ],
      [ "SkinVertex", "structrenderer_1_1SkinVertex.html", null ],
      [ "SlangVfs", "classrenderer_1_1SlangVfs.html", "classrenderer_1_1SlangVfs" ],
      [ "SsaoPass", "classrenderer_1_1SsaoPass.html", "classrenderer_1_1SsaoPass" ],
      [ "SsrPass", "classrenderer_1_1SsrPass.html", "classrenderer_1_1SsrPass" ],
      [ "TaaPass", "classrenderer_1_1TaaPass.html", "classrenderer_1_1TaaPass" ],
      [ "TextureUpload", "classrenderer_1_1TextureUpload.html", null ],
      [ "TonemapPass", "classrenderer_1_1TonemapPass.html", "classrenderer_1_1TonemapPass" ],
      [ "TracedShadowPass", "classrenderer_1_1TracedShadowPass.html", "classrenderer_1_1TracedShadowPass" ],
      [ "TrackedVolume", "structrenderer_1_1TrackedVolume.html", null ],
      [ "Vertex", "structrenderer_1_1Vertex.html", null ],
      [ "ViewportFrameDesc", "structrenderer_1_1ViewportFrameDesc.html", null ],
      [ "VolumeDelta", "structrenderer_1_1VolumeDelta.html", "structrenderer_1_1VolumeDelta" ],
      [ "VoxelCaster", "structrenderer_1_1VoxelCaster.html", null ],
      [ "VoxelChangeHistory", "classrenderer_1_1VoxelChangeHistory.html", "classrenderer_1_1VoxelChangeHistory" ],
      [ "VoxelChangeTracker", "classrenderer_1_1VoxelChangeTracker.html", "classrenderer_1_1VoxelChangeTracker" ],
      [ "VoxelGpuStorage", "classrenderer_1_1VoxelGpuStorage.html", "classrenderer_1_1VoxelGpuStorage" ],
      [ "VoxelInstanceGpu", "structrenderer_1_1VoxelInstanceGpu.html", null ],
      [ "VoxelPackedScene", "structrenderer_1_1VoxelPackedScene.html", null ],
      [ "VoxelPass", "classrenderer_1_1VoxelPass.html", "classrenderer_1_1VoxelPass" ],
      [ "VoxelRegion", "structrenderer_1_1VoxelRegion.html", null ],
      [ "VoxelScenePatcher", "classrenderer_1_1VoxelScenePatcher.html", "classrenderer_1_1VoxelScenePatcher" ],
      [ "VoxelScenePatchUpload", "classrenderer_1_1VoxelScenePatchUpload.html", "classrenderer_1_1VoxelScenePatchUpload" ],
      [ "VoxelSceneUpload", "classrenderer_1_1VoxelSceneUpload.html", null ],
      [ "VoxelStorageDebugInfo", "structrenderer_1_1VoxelStorageDebugInfo.html", "structrenderer_1_1VoxelStorageDebugInfo" ],
      [ "VulkanCore", "classrenderer_1_1VulkanCore.html", "classrenderer_1_1VulkanCore" ],
      [ "VulkanMesh", "classrenderer_1_1VulkanMesh.html", "classrenderer_1_1VulkanMesh" ],
      [ "VulkanPipeline", "classrenderer_1_1VulkanPipeline.html", "classrenderer_1_1VulkanPipeline" ],
      [ "VulkanRenderer", "classrenderer_1_1VulkanRenderer.html", "classrenderer_1_1VulkanRenderer" ],
      [ "VulkanSampler", "classrenderer_1_1VulkanSampler.html", null ],
      [ "VulkanSwapchain", "classrenderer_1_1VulkanSwapchain.html", null ],
      [ "VulkanTexture", "classrenderer_1_1VulkanTexture.html", "classrenderer_1_1VulkanTexture" ]
    ] ],
    [ "scripting", null, [
      [ "AssetProxy", "classscripting_1_1AssetProxy.html", "classscripting_1_1AssetProxy" ],
      [ "Color3", "structscripting_1_1Color3.html", null ],
      [ "Color4", "structscripting_1_1Color4.html", null ],
      [ "ListenerProxy", "classscripting_1_1ListenerProxy.html", null ],
      [ "LuaEventBinding", "structscripting_1_1LuaEventBinding.html", null ],
      [ "LuaEventDescriptor", "structscripting_1_1LuaEventDescriptor.html", null ],
      [ "LuaEventField", "structscripting_1_1LuaEventField.html", null ],
      [ "LuaEventRegistry", "classscripting_1_1LuaEventRegistry.html", null ],
      [ "LuaFunctionDesc", "structscripting_1_1LuaFunctionDesc.html", null ],
      [ "LuaGroup", "structscripting_1_1LuaGroup.html", null ],
      [ "LuaSignal", "classscripting_1_1LuaSignal.html", null ],
      [ "LuaState", "classscripting_1_1LuaState.html", "classscripting_1_1LuaState" ],
      [ "LuaSubgroup", "structscripting_1_1LuaSubgroup.html", null ],
      [ "LuaVarDesc", "structscripting_1_1LuaVarDesc.html", null ],
      [ "NodeProxy", "classscripting_1_1NodeProxy.html", "classscripting_1_1NodeProxy" ],
      [ "ScriptInstance", "classscripting_1_1ScriptInstance.html", "classscripting_1_1ScriptInstance" ],
      [ "ScriptNodeContextScope", "classscripting_1_1ScriptNodeContextScope.html", null ],
      [ "ScriptRuntime", "classscripting_1_1ScriptRuntime.html", "classscripting_1_1ScriptRuntime" ],
      [ "ScriptSchema", "structscripting_1_1ScriptSchema.html", "structscripting_1_1ScriptSchema" ],
      [ "SignalProxy", "classscripting_1_1SignalProxy.html", null ],
      [ "TypeMarker", "structscripting_1_1TypeMarker.html", null ],
      [ "UIBindsProxy", "classscripting_1_1UIBindsProxy.html", null ],
      [ "Vec3FieldProxy", "classscripting_1_1Vec3FieldProxy.html", null ]
    ] ],
    [ "signals", null, [
      [ "ConnectionInfo", "structsignals_1_1ConnectionInfo.html", null ]
    ] ],
    [ "std", null, [
      [ "formatter&lt; toast::Box&lt; T &gt; &gt;", "structstd_1_1formatter_3_01toast_1_1Box_3_01T_01_4_01_4.html", null ],
      [ "formatter&lt; toast::UID &gt;", "structstd_1_1formatter_3_01toast_1_1UID_01_4.html", null ],
      [ "hash&lt; toast::_detail::ControlBox &gt;", "structstd_1_1hash_3_01toast_1_1__detail_1_1ControlBox_01_4.html", null ],
      [ "hash&lt; toast::Box&lt; T &gt; &gt;", "structstd_1_1hash_3_01toast_1_1Box_3_01T_01_4_01_4.html", null ]
    ] ],
    [ "toast", null, [
      [ "_detail", "namespacetoast_1_1__detail.html", [
        [ "Accessor", "structtoast_1_1__detail_1_1Accessor.html", null ],
        [ "ControlBox", "structtoast_1_1__detail_1_1ControlBox.html", "structtoast_1_1__detail_1_1ControlBox" ],
        [ "Defer", "structtoast_1_1__detail_1_1Defer.html", null ],
        [ "NodeCluster", "structtoast_1_1__detail_1_1NodeCluster.html", null ],
        [ "Robber", "structtoast_1_1__detail_1_1Robber.html", null ],
        [ "TickSchedule", "structtoast_1_1__detail_1_1TickSchedule.html", null ],
        [ "WorldTestAccess", "structtoast_1_1__detail_1_1WorldTestAccess.html", "structtoast_1_1__detail_1_1WorldTestAccess" ]
      ] ],
      [ "input", null, [
        [ "TrackpadTransform", "structtoast_1_1input_1_1TrackpadTransform.html", null ],
        [ "TrackpadDelta", "structtoast_1_1input_1_1TrackpadDelta.html", null ],
        [ "TrackpadGesture", "classtoast_1_1input_1_1TrackpadGesture.html", null ]
      ] ],
      [ "settings", null, [
        [ "Meta", "structtoast_1_1settings_1_1Meta.html", "structtoast_1_1settings_1_1Meta" ],
        [ "Entry", "structtoast_1_1settings_1_1Entry.html", "structtoast_1_1settings_1_1Entry" ],
        [ "Settings", "classtoast_1_1settings_1_1Settings.html", "classtoast_1_1settings_1_1Settings" ],
        [ "Setting", "classtoast_1_1settings_1_1Setting.html", "classtoast_1_1settings_1_1Setting" ]
      ] ],
      [ "AmbienceVolume", "classtoast_1_1AmbienceVolume.html", "classtoast_1_1AmbienceVolume" ],
      [ "AmbientLight", "classtoast_1_1AmbientLight.html", null ],
      [ "AnimationPlayer", "classtoast_1_1AnimationPlayer.html", "classtoast_1_1AnimationPlayer" ],
      [ "AssetArrayFieldAccess", "structtoast_1_1AssetArrayFieldAccess.html", null ],
      [ "AssetFieldAccess", "structtoast_1_1AssetFieldAccess.html", null ],
      [ "AudioBoxEmitter", "classtoast_1_1AudioBoxEmitter.html", "classtoast_1_1AudioBoxEmitter" ],
      [ "AudioCapsuleEmitter", "classtoast_1_1AudioCapsuleEmitter.html", "classtoast_1_1AudioCapsuleEmitter" ],
      [ "AudioContext", "classtoast_1_1AudioContext.html", null ],
      [ "AudioEmitter", "classtoast_1_1AudioEmitter.html", "classtoast_1_1AudioEmitter" ],
      [ "AudioEmitter3D", "classtoast_1_1AudioEmitter3D.html", "classtoast_1_1AudioEmitter3D" ],
      [ "AudioEmitterBase", "classtoast_1_1AudioEmitterBase.html", "classtoast_1_1AudioEmitterBase" ],
      [ "AudioListener", "classtoast_1_1AudioListener.html", null ],
      [ "AudioSphereEmitter", "classtoast_1_1AudioSphereEmitter.html", "classtoast_1_1AudioSphereEmitter" ],
      [ "AudioVolume", "classtoast_1_1AudioVolume.html", "classtoast_1_1AudioVolume" ],
      [ "Box", "classtoast_1_1Box.html", "classtoast_1_1Box" ],
      [ "Camera", "classtoast_1_1Camera.html", "classtoast_1_1Camera" ],
      [ "CameraController", "classtoast_1_1CameraController.html", "classtoast_1_1CameraController" ],
      [ "CarveVolume", "classtoast_1_1CarveVolume.html", null ],
      [ "DirectionalLight", "classtoast_1_1DirectionalLight.html", null ],
      [ "EditorCameraController", "classtoast_1_1EditorCameraController.html", "classtoast_1_1EditorCameraController" ],
      [ "Engine", "classtoast_1_1Engine.html", "classtoast_1_1Engine" ],
      [ "EnginePimpl", "structtoast_1_1EnginePimpl.html", null ],
      [ "EnumFieldAccess", "structtoast_1_1EnumFieldAccess.html", null ],
      [ "EventInfo", "structtoast_1_1EventInfo.html", null ],
      [ "EventRegistry", "classtoast_1_1EventRegistry.html", null ],
      [ "FieldAccess", "structtoast_1_1FieldAccess.html", null ],
      [ "FieldAccess&lt; Class, Box&lt; T &gt;, Tag &gt;", "structtoast_1_1FieldAccess_3_01Class_00_01Box_3_01T_01_4_00_01Tag_01_4.html", null ],
      [ "FieldInfo", "structtoast_1_1FieldInfo.html", "structtoast_1_1FieldInfo" ],
      [ "FillVolume", "classtoast_1_1FillVolume.html", null ],
      [ "FunctionInfo", "structtoast_1_1FunctionInfo.html", "structtoast_1_1FunctionInfo" ],
      [ "GameplaySettings", "classtoast_1_1GameplaySettings.html", null ],
      [ "GroupInfo", "structtoast_1_1GroupInfo.html", "structtoast_1_1GroupInfo" ],
      [ "IApplication", "classtoast_1_1IApplication.html", null ],
      [ "IBaseWindow", "classtoast_1_1IBaseWindow.html", null ],
      [ "INodeOwner", "classtoast_1_1INodeOwner.html", "classtoast_1_1INodeOwner" ],
      [ "IrradianceVolume", "classtoast_1_1IrradianceVolume.html", "classtoast_1_1IrradianceVolume" ],
      [ "Light", "classtoast_1_1Light.html", "classtoast_1_1Light" ],
      [ "LuaVarDesc", "structtoast_1_1LuaVarDesc.html", null ],
      [ "MeshNode", "classtoast_1_1MeshNode.html", "classtoast_1_1MeshNode" ],
      [ "MusicPlayer", "classtoast_1_1MusicPlayer.html", "classtoast_1_1MusicPlayer" ],
      [ "Node", "classtoast_1_1Node.html", "classtoast_1_1Node" ],
      [ "Node3D", "classtoast_1_1Node3D.html", "classtoast_1_1Node3D" ],
      [ "NodeInfo", "structtoast_1_1NodeInfo.html", "structtoast_1_1NodeInfo" ],
      [ "NodeMessage", "structtoast_1_1NodeMessage.html", null ],
      [ "NodeRegistry", "classtoast_1_1NodeRegistry.html", null ],
      [ "NodeTypeInfo", "structtoast_1_1NodeTypeInfo.html", null ],
      [ "PaintVolume", "classtoast_1_1PaintVolume.html", null ],
      [ "Panel", "classtoast_1_1Panel.html", null ],
      [ "Panel3D", "classtoast_1_1Panel3D.html", null ],
      [ "PanelContext", "classtoast_1_1PanelContext.html", null ],
      [ "ParameterInfo", "structtoast_1_1ParameterInfo.html", null ],
      [ "PhysicsSettings", "classtoast_1_1PhysicsSettings.html", null ],
      [ "PlayWorkspace", "classtoast_1_1PlayWorkspace.html", "classtoast_1_1PlayWorkspace" ],
      [ "PointLight", "classtoast_1_1PointLight.html", null ],
      [ "PostProcessVolume", "classtoast_1_1PostProcessVolume.html", "classtoast_1_1PostProcessVolume" ],
      [ "PrintTextNode", "classtoast_1_1PrintTextNode.html", null ],
      [ "ProceduralVoxel", "classtoast_1_1ProceduralVoxel.html", "classtoast_1_1ProceduralVoxel" ],
      [ "ProjectSettings", "classtoast_1_1ProjectSettings.html", null ],
      [ "Ray", "structtoast_1_1Ray.html", null ],
      [ "Reflect", "classtoast_1_1Reflect.html", null ],
      [ "Reflect&lt; event::_detail::IEvent &gt;", "structtoast_1_1Reflect_3_01event_1_1__detail_1_1IEvent_01_4.html", null ],
      [ "ReflectionProbe", "classtoast_1_1ReflectionProbe.html", "classtoast_1_1ReflectionProbe" ],
      [ "SDLWindow", "classtoast_1_1SDLWindow.html", null ],
      [ "SignalInfo", "structtoast_1_1SignalInfo.html", null ],
      [ "SnapshotVolume", "classtoast_1_1SnapshotVolume.html", "classtoast_1_1SnapshotVolume" ],
      [ "Spotlight", "classtoast_1_1Spotlight.html", null ],
      [ "State", "structtoast_1_1State.html", null ],
      [ "StateMachine", "classtoast_1_1StateMachine.html", null ],
      [ "SubgroupInfo", "structtoast_1_1SubgroupInfo.html", "structtoast_1_1SubgroupInfo" ],
      [ "TestNode1", "classtoast_1_1TestNode1.html", null ],
      [ "TestNode2", "classtoast_1_1TestNode2.html", null ],
      [ "ThreadPool", "classtoast_1_1ThreadPool.html", "classtoast_1_1ThreadPool" ],
      [ "TickFunctions", "structtoast_1_1TickFunctions.html", "structtoast_1_1TickFunctions" ],
      [ "TickScheduler", "classtoast_1_1TickScheduler.html", "classtoast_1_1TickScheduler" ],
      [ "Transition", "structtoast_1_1Transition.html", null ],
      [ "UID", "structtoast_1_1UID.html", "structtoast_1_1UID" ],
      [ "UISettings", "classtoast_1_1UISettings.html", "classtoast_1_1UISettings" ],
      [ "VectorStreamBuf", "structtoast_1_1VectorStreamBuf.html", null ],
      [ "Volume", "classtoast_1_1Volume.html", "classtoast_1_1Volume" ],
      [ "VolumeTarget", "structtoast_1_1VolumeTarget.html", "structtoast_1_1VolumeTarget" ],
      [ "Voxel", "classtoast_1_1Voxel.html", null ],
      [ "VoxelBucket", "classtoast_1_1VoxelBucket.html", "classtoast_1_1VoxelBucket" ],
      [ "VoxelGroup", "classtoast_1_1VoxelGroup.html", "classtoast_1_1VoxelGroup" ],
      [ "VoxelMesh", "classtoast_1_1VoxelMesh.html", "classtoast_1_1VoxelMesh" ],
      [ "VoxelNode", "classtoast_1_1VoxelNode.html", "classtoast_1_1VoxelNode" ],
      [ "VoxelPiece", "classtoast_1_1VoxelPiece.html", "classtoast_1_1VoxelPiece" ],
      [ "VoxelVolume", "classtoast_1_1VoxelVolume.html", "classtoast_1_1VoxelVolume" ],
      [ "Workspace", "classtoast_1_1Workspace.html", "classtoast_1_1Workspace" ],
      [ "WorkspaceHistory", "classtoast_1_1WorkspaceHistory.html", "classtoast_1_1WorkspaceHistory" ],
      [ "World", "classtoast_1_1World.html", "classtoast_1_1World" ]
    ] ],
    [ "ui", null, [
      [ "DocumentScan", "structui_1_1DocumentScan.html", null ],
      [ "PreprocessContext", "structui_1_1PreprocessContext.html", null ],
      [ "TextFormatContext", "structui_1_1TextFormatContext.html", null ],
      [ "TgaImage", "structui_1_1TgaImage.html", null ],
      [ "UIBinds", "classui_1_1UIBinds.html", "classui_1_1UIBinds" ],
      [ "UIBindStore", "classui_1_1UIBindStore.html", null ],
      [ "UIFileInterface", "classui_1_1UIFileInterface.html", null ],
      [ "UIInputRouter", "classui_1_1UIInputRouter.html", null ],
      [ "UIPass", "classui_1_1UIPass.html", "classui_1_1UIPass" ],
      [ "UISystem", "classui_1_1UISystem.html", "classui_1_1UISystem" ],
      [ "UISystemInterface", "classui_1_1UISystemInterface.html", null ],
      [ "WorldUIPass", "classui_1_1WorldUIPass.html", "classui_1_1WorldUIPass" ]
    ] ],
    [ "voxel", null, [
      [ "gpu", null, [
        [ "VolumeRecord", "structvoxel_1_1gpu_1_1VolumeRecord.html", "structvoxel_1_1gpu_1_1VolumeRecord" ],
        [ "PackedPool", "structvoxel_1_1gpu_1_1PackedPool.html", "structvoxel_1_1gpu_1_1PackedPool" ],
        [ "SceneVolume", "structvoxel_1_1gpu_1_1SceneVolume.html", null ],
        [ "PackedScene", "structvoxel_1_1gpu_1_1PackedScene.html", "structvoxel_1_1gpu_1_1PackedScene" ],
        [ "SceneLayout", "structvoxel_1_1gpu_1_1SceneLayout.html", null ],
        [ "PatchRun", "structvoxel_1_1gpu_1_1PatchRun.html", null ],
        [ "PatchSection", "structvoxel_1_1gpu_1_1PatchSection.html", "structvoxel_1_1gpu_1_1PatchSection" ],
        [ "TagDelta", "structvoxel_1_1gpu_1_1TagDelta.html", null ],
        [ "ScenePatch", "structvoxel_1_1gpu_1_1ScenePatch.html", "structvoxel_1_1gpu_1_1ScenePatch" ],
        [ "VolumeDirty", "structvoxel_1_1gpu_1_1VolumeDirty.html", null ]
      ] ],
      [ "BrickCoord", "structvoxel_1_1BrickCoord.html", null ],
      [ "BrickEntry", "structvoxel_1_1BrickEntry.html", "structvoxel_1_1BrickEntry" ],
      [ "BrickExtent", "structvoxel_1_1BrickExtent.html", null ],
      [ "BrickFaces", "structvoxel_1_1BrickFaces.html", null ],
      [ "BrickNeighbourhood", "structvoxel_1_1BrickNeighbourhood.html", null ],
      [ "BrickOccupancy", "structvoxel_1_1BrickOccupancy.html", null ],
      [ "BrickPiece", "structvoxel_1_1BrickPiece.html", null ],
      [ "BrickPool", "classvoxel_1_1BrickPool.html", "classvoxel_1_1BrickPool" ],
      [ "Connectivity", "structvoxel_1_1Connectivity.html", null ],
      [ "EditBounds", "structvoxel_1_1EditBounds.html", null ],
      [ "EditResult", "structvoxel_1_1EditResult.html", null ],
      [ "LatticeOrientation", "structvoxel_1_1LatticeOrientation.html", null ],
      [ "LatticePlacement", "structvoxel_1_1LatticePlacement.html", null ],
      [ "MassMoments", "structvoxel_1_1MassMoments.html", "structvoxel_1_1MassMoments" ],
      [ "MassProperties", "structvoxel_1_1MassProperties.html", "structvoxel_1_1MassProperties" ],
      [ "MaterialLibrary", "structvoxel_1_1MaterialLibrary.html", null ],
      [ "Palette", "structvoxel_1_1Palette.html", null ],
      [ "PaletteEntry", "structvoxel_1_1PaletteEntry.html", "structvoxel_1_1PaletteEntry" ],
      [ "PaletteRemap", "structvoxel_1_1PaletteRemap.html", null ],
      [ "PhysicalMaterial", "structvoxel_1_1PhysicalMaterial.html", "structvoxel_1_1PhysicalMaterial" ],
      [ "RayHit", "structvoxel_1_1RayHit.html", "structvoxel_1_1RayHit" ],
      [ "Region", "structvoxel_1_1Region.html", null ],
      [ "StampResult", "structvoxel_1_1StampResult.html", "structvoxel_1_1StampResult" ],
      [ "SurfaceVoxel", "structvoxel_1_1SurfaceVoxel.html", "structvoxel_1_1SurfaceVoxel" ],
      [ "TableProblem", "structvoxel_1_1TableProblem.html", null ],
      [ "TileOptions", "structvoxel_1_1TileOptions.html", "structvoxel_1_1TileOptions" ],
      [ "Volume", "classvoxel_1_1Volume.html", "classvoxel_1_1Volume" ],
      [ "VolumeHit", "structvoxel_1_1VolumeHit.html", "structvoxel_1_1VolumeHit" ],
      [ "VolumeSurface", "classvoxel_1_1VolumeSurface.html", null ],
      [ "WriteBrush", "structvoxel_1_1WriteBrush.html", null ]
    ] ],
    [ "FrameResources", "structFrameResources.html", null ],
    [ "IComputePass", "classIComputePass.html", null ],
    [ "IRenderPass", "classIRenderPass.html", "classIRenderPass" ],
    [ "MyGame", "classMyGame.html", null ],
    [ "RenderInterface_VK", "classRenderInterface__VK.html", "classRenderInterface__VK" ],
    [ "Time", "classTime.html", "classTime" ],
    [ "TimeSnapshot", "structTimeSnapshot.html", null ]
];