var dir_86f88daaaf08922b03db05b762deb37a =
[
    [ "animation.hpp", "animation_8hpp.html", "animation_8hpp" ],
    [ "asset_field_access.hpp", "asset__field__access_8hpp.html", "asset__field__access_8hpp" ],
    [ "asset_manager.hpp", "asset__manager_8hpp.html", "asset__manager_8hpp" ],
    [ "asset_registry.hpp", "asset__registry_8hpp_source.html", null ],
    [ "assets.hpp", "assets_2assets_8hpp.html", "assets_2assets_8hpp" ],
    [ "core_types.hpp", "core__types_8hpp.html", "core__types_8hpp" ],
    [ "curve.hpp", "curve_8hpp.html", "curve_8hpp" ],
    [ "data.hpp", "data_8hpp.html", "data_8hpp" ],
    [ "data_schema_codegen.hpp", "data__schema__codegen_8hpp.html", "data__schema__codegen_8hpp" ],
    [ "data_value.hpp", "data__value_8hpp.html", "data__value_8hpp" ],
    [ "gltf_importer.hpp", "gltf__importer_8hpp.html", null ],
    [ "hdr_image.cpp", "hdr__image_8cpp.html", "hdr__image_8cpp" ],
    [ "hdr_image.hpp", "hdr__image_8hpp.html", "hdr__image_8hpp" ],
    [ "material.hpp", "material_8hpp.html", "material_8hpp" ],
    [ "material_instance.hpp", "material__instance_8hpp.html", "material__instance_8hpp" ],
    [ "mesh.hpp", "mesh_8hpp.html", "mesh_8hpp" ],
    [ "pack.hpp", "pack_8hpp.html", "pack_8hpp" ],
    [ "prefab.hpp", "prefab_8hpp_source.html", null ],
    [ "schema.hpp", "schema_8hpp.html", "schema_8hpp" ],
    [ "script.hpp", "script_8hpp.html", "script_8hpp" ],
    [ "shader.hpp", "shader_8hpp.html", "shader_8hpp" ],
    [ "texture.hpp", "texture_8hpp.html", "texture_8hpp" ],
    [ "types.hpp", "types_8hpp.html", null ]
];