var namespaces_dup =
[
    [ "editor", "namespaceeditor.html", "namespaceeditor" ],
    [ "toast", null, [
      [ "_detail", "namespacetoast_1_1__detail.html", "namespacetoast_1_1__detail" ],
      [ "AmbienceVolume", "classtoast_1_1AmbienceVolume.html", "classtoast_1_1AmbienceVolume" ],
      [ "AmbientLight", "classtoast_1_1AmbientLight.html", null ],
      [ "AnimationPlayer", "classtoast_1_1AnimationPlayer.html", "classtoast_1_1AnimationPlayer" ],
      [ "AssetArrayFieldAccess", "structtoast_1_1AssetArrayFieldAccess.html", null ],
      [ "AssetFieldAccess", "structtoast_1_1AssetFieldAccess.html", null ],
      [ "AudioBoxEmitter", "classtoast_1_1AudioBoxEmitter.html", "classtoast_1_1AudioBoxEmitter" ],
      [ "AudioCapsuleEmitter", "classtoast_1_1AudioCapsuleEmitter.html", "classtoast_1_1AudioCapsuleEmitter" ],
      [ "AudioContext", "classtoast_1_1AudioContext.html", null ],
      [ "AudioEmitter", "classtoast_1_1AudioEmitter.html", "classtoast_1_1AudioEmitter" ],
      [ "AudioEmitter3D", "classtoast_1_1AudioEmitter3D.html", "classtoast_1_1AudioEmitter3D" ],
      [ "AudioEmitterBase", "classtoast_1_1AudioEmitterBase.html", "classtoast_1_1AudioEmitterBase" ],
      [ "AudioListener", "classtoast_1_1AudioListener.html", null ],
      [ "AudioSphereEmitter", "classtoast_1_1AudioSphereEmitter.html", "classtoast_1_1AudioSphereEmitter" ],
      [ "AudioVolume", "classtoast_1_1AudioVolume.html", "classtoast_1_1AudioVolume" ],
      [ "Box", "classtoast_1_1Box.html", "classtoast_1_1Box" ],
      [ "Camera", "classtoast_1_1Camera.html", "classtoast_1_1Camera" ],
      [ "CameraController", "classtoast_1_1CameraController.html", "classtoast_1_1CameraController" ],
      [ "DirectionalLight", "classtoast_1_1DirectionalLight.html", null ],
      [ "EditorCameraController", "classtoast_1_1EditorCameraController.html", "classtoast_1_1EditorCameraController" ],
      [ "Engine", "classtoast_1_1Engine.html", "classtoast_1_1Engine" ],
      [ "EnginePimpl", "structtoast_1_1EnginePimpl.html", null ],
      [ "EnumFieldAccess", "structtoast_1_1EnumFieldAccess.html", null ],
      [ "EventInfo", "structtoast_1_1EventInfo.html", null ],
      [ "EventRegistry", "classtoast_1_1EventRegistry.html", null ],
      [ "FieldAccess", "structtoast_1_1FieldAccess.html", null ],
      [ "FieldAccess&lt; Class, Box&lt; T &gt;, Tag &gt;", "structtoast_1_1FieldAccess_3_01Class_00_01Box_3_01T_01_4_00_01Tag_01_4.html", null ],
      [ "FieldInfo", "structtoast_1_1FieldInfo.html", "structtoast_1_1FieldInfo" ],
      [ "FunctionInfo", "structtoast_1_1FunctionInfo.html", "structtoast_1_1FunctionInfo" ],
      [ "GameplaySettings", "classtoast_1_1GameplaySettings.html", null ],
      [ "GroupInfo", "structtoast_1_1GroupInfo.html", "structtoast_1_1GroupInfo" ],
      [ "IApplication", "classtoast_1_1IApplication.html", null ],
      [ "IBaseWindow", "classtoast_1_1IBaseWindow.html", null ],
      [ "INodeOwner", "classtoast_1_1INodeOwner.html", "classtoast_1_1INodeOwner" ],
      [ "IrradianceVolume", "classtoast_1_1IrradianceVolume.html", "classtoast_1_1IrradianceVolume" ],
      [ "Light", "classtoast_1_1Light.html", "classtoast_1_1Light" ],
      [ "LuaVarDesc", "structtoast_1_1LuaVarDesc.html", null ],
      [ "MeshNode", "classtoast_1_1MeshNode.html", "classtoast_1_1MeshNode" ],
      [ "MusicPlayer", "classtoast_1_1MusicPlayer.html", "classtoast_1_1MusicPlayer" ],
      [ "Node", "classtoast_1_1Node.html", "classtoast_1_1Node" ],
      [ "Node3D", "classtoast_1_1Node3D.html", "classtoast_1_1Node3D" ],
      [ "NodeInfo", "structtoast_1_1NodeInfo.html", "structtoast_1_1NodeInfo" ],
      [ "NodeMessage", "structtoast_1_1NodeMessage.html", null ],
      [ "NodeRegistry", "classtoast_1_1NodeRegistry.html", null ],
      [ "Panel", "classtoast_1_1Panel.html", null ],
      [ "Panel3D", "classtoast_1_1Panel3D.html", null ],
      [ "PanelContext", "classtoast_1_1PanelContext.html", null ],
      [ "ParameterInfo", "structtoast_1_1ParameterInfo.html", null ],
      [ "PhysicsSettings", "classtoast_1_1PhysicsSettings.html", null ],
      [ "PlayWorkspace", "classtoast_1_1PlayWorkspace.html", "classtoast_1_1PlayWorkspace" ],
      [ "PointLight", "classtoast_1_1PointLight.html", null ],
      [ "PostProcessVolume", "classtoast_1_1PostProcessVolume.html", "classtoast_1_1PostProcessVolume" ],
      [ "PrintTextNode", "classtoast_1_1PrintTextNode.html", null ],
      [ "ProjectSettings", "classtoast_1_1ProjectSettings.html", null ],
      [ "Ray", "structtoast_1_1Ray.html", null ],
      [ "Reflect", "classtoast_1_1Reflect.html", null ],
      [ "Reflect&lt; event::_detail::IEvent &gt;", "structtoast_1_1Reflect_3_01event_1_1__detail_1_1IEvent_01_4.html", null ],
      [ "ReflectionProbe", "classtoast_1_1ReflectionProbe.html", "classtoast_1_1ReflectionProbe" ],
      [ "SDLWindow", "classtoast_1_1SDLWindow.html", null ],
      [ "SignalInfo", "structtoast_1_1SignalInfo.html", null ],
      [ "SnapshotVolume", "classtoast_1_1SnapshotVolume.html", "classtoast_1_1SnapshotVolume" ],
      [ "Spotlight", "classtoast_1_1Spotlight.html", null ],
      [ "State", "structtoast_1_1State.html", null ],
      [ "StateMachine", "classtoast_1_1StateMachine.html", null ],
      [ "SubgroupInfo", "structtoast_1_1SubgroupInfo.html", "structtoast_1_1SubgroupInfo" ],
      [ "TestNode1", "classtoast_1_1TestNode1.html", null ],
      [ "TestNode2", "classtoast_1_1TestNode2.html", null ],
      [ "ThreadPool", "classtoast_1_1ThreadPool.html", "classtoast_1_1ThreadPool" ],
      [ "TickFunctions", "structtoast_1_1TickFunctions.html", "structtoast_1_1TickFunctions" ],
      [ "TickScheduler", "classtoast_1_1TickScheduler.html", "classtoast_1_1TickScheduler" ],
      [ "Transition", "structtoast_1_1Transition.html", null ],
      [ "UID", "structtoast_1_1UID.html", "structtoast_1_1UID" ],
      [ "UISettings", "classtoast_1_1UISettings.html", "classtoast_1_1UISettings" ],
      [ "VectorStreamBuf", "structtoast_1_1VectorStreamBuf.html", null ],
      [ "Volume", "classtoast_1_1Volume.html", "classtoast_1_1Volume" ],
      [ "VolumeTarget", "structtoast_1_1VolumeTarget.html", "structtoast_1_1VolumeTarget" ],
      [ "VoxelNode", "classtoast_1_1VoxelNode.html", "classtoast_1_1VoxelNode" ],
      [ "Workspace", "classtoast_1_1Workspace.html", "classtoast_1_1Workspace" ],
      [ "WorkspaceHistory", "classtoast_1_1WorkspaceHistory.html", "classtoast_1_1WorkspaceHistory" ],
      [ "World", "classtoast_1_1World.html", "classtoast_1_1World" ],
      [ "GizmoHandle", "gizmo__layout_8hpp.html#a97503304f8d31e85c7550dbe2d54ef47", null ],
      [ "GizmoTool", "gizmo__layout_8hpp.html#a26ba0ceff8dbf69c21a2df47c1941d16", null ],
      [ "LightType", "light_8hpp.html#a8d3f9ea58e98a7ef1ef78bc531a0a5b5", null ],
      [ "NodeState", "node_8hpp.html#a98d11435d9b92e9901a40a71793fd680", [
        [ "root", "node_8hpp.html#a98d11435d9b92e9901a40a71793fd680a63a9f0ea7bb98050796b649e85481845", null ],
        [ "cached", "node_8hpp.html#a98d11435d9b92e9901a40a71793fd680a1fb1a060534164a18a99494122825190", null ],
        [ "global", "node_8hpp.html#a98d11435d9b92e9901a40a71793fd680a9c70933aff6b2a6d08c687a6cbb6b765", null ],
        [ "loading", "node_8hpp.html#a98d11435d9b92e9901a40a71793fd680aa14fa2166ed698f3d04061f57e5ab9b9", null ],
        [ "destroy", "node_8hpp.html#a98d11435d9b92e9901a40a71793fd680afb14982288108e1fbd6207ef55f05027", null ]
      ] ],
      [ "NodeType", "node_8hpp.html#aea15e3db2fb9b67d5f99b3436f6a73fa", [
        [ "child", "node_8hpp.html#aea15e3db2fb9b67d5f99b3436f6a73faa1b7d5726533ab525a8760351e9b5e415", null ],
        [ "root", "node_8hpp.html#aea15e3db2fb9b67d5f99b3436f6a73faa63a9f0ea7bb98050796b649e85481845", null ],
        [ "world_root", "node_8hpp.html#aea15e3db2fb9b67d5f99b3436f6a73faa139ff2c4fb5263e1ab4247457c03400e", null ]
      ] ],
      [ "TickFunctionList", "reflect__node_8hpp.html#ad08c233710fd0f56aefc18a7a9f1db5a", null ],
      [ "setArtworkPath", "uri__handler_8hpp.html#ad3fc4f25272e1bca6ea7892f6359e61c", null ],
      [ "setAssetsPath", "uri__handler_8hpp.html#ac00ab098ca7137e5151e4e8974fcad3e", null ]
    ] ]
];