#include "ui_system.hpp"

#include "ui_file_interface.hpp"
#include "ui_system_interface.hpp"

#include <RmlUi/Core.h>
#include <cassert>
#include <toast/log.hpp>
#include <tracy/Tracy.hpp>

namespace ui {

UISystem::UISystem() noexcept {
	ZoneScoped;
	TOAST_ASSERT(not instance, "UI", "UISystem already exists");
	instance = this;

	m_file_interface = std::make_unique<UIFileInterface>();
	m_system_interface = std::make_unique<UISystemInterface>();

	Rml::SetFileInterface(m_file_interface.get());
	Rml::SetSystemInterface(m_system_interface.get());

	if (!Rml::Initialise()) {
		TOAST_ERROR("UI", "RmlUi failed to initialise");
		return;
	}

	TOAST_INFO("UI", "RmlUi {} initialised", Rml::GetVersion());
}

UISystem::~UISystem() noexcept {
	Rml::Shutdown();
	instance = nullptr;
}

auto UISystem::get() noexcept -> UISystem& {
	TOAST_ASSERT(instance, "UI", "UISystem doesn't exist");
	return *instance;
}

auto UISystem::exists() noexcept -> bool {
	return instance != nullptr;
}

void UISystem::tick() noexcept {
	ZoneScoped;

	/*
	 * TODO: We need to call render here i believe
	 *
	 * [ TICK THREAD ]
	 * 1. Call context->Update() to let RmlUi resolve layout, flexbox, and animations
	 * 2. Call context->Render() -> Customize RenderInterface to DEEP COPY vertices,
	 *    indices, scissors, and texture IDs into a thread-safe staging buffer
	 * 3. Pack all copied geometry into a UI Render proxy
	 * 4. Push the proxy to the Vulkan render thread
	 *
	 * [ VULKAN RENDER THREAD ]
	 * 1. Receive the proxy generated by the logic thread
	 * 2. If geometry changed, update the corresponding Vulkan staging and device host-visible buffers
	 * 3. Record Vulkan commands
	 * 4. Submit the command buffer to the graphics queue
	 */

	for (int i = 0; i < Rml::GetNumContexts(); i++) {
		Rml::GetContext(i)->Update();
	}
}

auto UISystem::createContext(std::string_view name, glm::ivec2 dimensions) -> Rml::Context* {
	// RmlUi requires globally unique context names
	const auto unique_name = std::format("{}#{}", name, m_next_context_id++);
	Rml::Context* context = Rml::CreateContext(unique_name, {dimensions.x, dimensions.y});
	if (!context) {
		TOAST_ERROR("UI", "Failed to create context '{}'", unique_name);
		return nullptr;
	}

	TOAST_TRACE("UI", "Created context '{}' ({}x{})", unique_name, dimensions.x, dimensions.y);
	return context;
}

void UISystem::destroyContext(Rml::Context* context) {
	if (!context) {
		return;
	}
	Rml::RemoveContext(context->GetName());
}

auto UISystem::loadFontFace(std::string_view uri, bool fallback) -> bool {
	ZoneScoped;

	if (!Rml::LoadFontFace(Rml::String(uri), fallback)) {
		TOAST_WARN("UI", "Failed to load font face '{}'", uri);
		return false;
	}

	TOAST_TRACE("UI", "Loaded font face '{}'", uri);
	return true;
}

}
