<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>crash_reporter</RootNamespace>
        <AssemblyName>crash_reporter</AssemblyName>
        <Company>nullptr Studios</Company>
    </PropertyGroup>

    <!-- The crash handler looks for out/<Config>/crash_reporter/crash_reporter.exe -->
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>../../out/Debug/crash_reporter</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>../../out/Release/crash_reporter</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.3" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
    </ItemGroup>

</Project>
