// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogData {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
    #[prost(enumeration = "log_data::Severity", tag = "2")]
    pub severity: i32,
    #[prost(string, tag = "3")]
    pub filepath: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub line_number: u32,
    #[prost(string, tag = "5")]
    pub sink: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `LogData`.
pub mod log_data {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Severity {
        Trace = 0,
        Info = 1,
        Warning = 2,
        Error = 3,
        Critical = 4,
    }
    impl Severity {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Trace => "TRACE",
                Self::Info => "INFO",
                Self::Warning => "WARNING",
                Self::Error => "ERROR",
                Self::Critical => "CRITICAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TRACE" => Some(Self::Trace),
                "INFO" => Some(Self::Info),
                "WARNING" => Some(Self::Warning),
                "ERROR" => Some(Self::Error),
                "CRITICAL" => Some(Self::Critical),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogBatch {
    #[prost(message, repeated, tag = "1")]
    pub logs: ::prost::alloc::vec::Vec<LogData>,
}
