#pragma once
#include <string>

namespace {
inline const std::string sample_text =
	"~format @int = 2\n"
	"\n"
	"[station_master type=SpaceStationManager]\n"
	"id @string = 4e3d2c1b0a9\n"
	"sector_name @string = Kepler Orbital Outpost Delta\n"
	"orbit_radius_km @float = 42164\n"
	"is_pressurized @bool = true\n"
	"\n"
	"[nebula_field type=CosmicParticleEmitter]\n"
	"parent @string = station_master\n"
	"id @string = 8f7e6d5c4b3\n"
	"enabled @bool = true\n"
	".emitter_settings\n"
	"    max_particles @int = 75000\n"
	"    texture_sheet_path @string = assets/textures/vfx/cosmic dust/nebula_cloud.png\n"
	"    spawn_rate @float = 250\n"
	"    ..kinematics\n"
	"        velocity_over_lifetime @vec3 = 0.02 -0.005 0.08\n"
	"        particle_lifetime_range @vec2 = 12 45\n"
	"        orbital_pull_centers @array_string = local_stellar_core\x1f" "collapsed_singularity\n"
	"\n"
	"[defense_node_alpha type=AutomatedTurret]\n"
	"parent @string = 4e3d2c1b0a9\n"
	"id @string = a1b2c3d4e5f\n"
	"enabled @bool = true\n"
	".transform\n"
	"    position @vec3 = 45.5 12 -118.4\n"
	"    rotation @vec4 = 0 0.382 0 0.924\n"
	"    scale @vec3 = 2 2 2\n"
	".weapon_system\n"
	"    fire_rate @float = 0.12\n"
	"    ammo_types_available @array_string = plasma_bolt\x1f" "emp_slug\x1f" "kinetic_disruptor\n"
	"    barrel_heat_dissipation @float = 15.4\n"
	"    ..targeting_matrix\n"
	"        scan_radius @float = 250\n"
	"        tracking_speed_deg @float = 90\n"
	"        priority_targets @array_string = raider_interceptor\x1f" "rogue_mining_drone\x1f" "debris_hazard\n"
	"        blind_angle_bounds @array_float = 180 245\n"
	"\n"
	"[player_avatar type=PlayerEntity]\n"
	"parent @string = a1b2c3d4e5f\n"
	"id @string = 7a8b9c0d1e2\n"
	"enabled @bool = true\n"
	".transform\n"
	"    position @vec3 = 3.42 0 12.15\n"
	"    rotation @vec4 = 0 1 0 0\n"
	"    scale @vec3 = 1 1 1\n"
	".mesh_renderer\n"
	"    base_rig_path @string = assets/models/characters/avatar skeleton/human_base.fbx\n"
	"    lod_distances @array_float = 5 15 45\n"
	".wardrobe_manager\n"
	"    equipped_outfit_id @string = deep_space_vanguard_set\n"
	"    apparel_layers @array_string = base_thermal_mesh\x1f" "ballistic_breastplate\x1f" "reflective_visor\x1f" "heavy_trench_cloak\n"
	"    color_palette_hex @array_string = #1a1a1a\x1f" "#d4af37\x1f" "#e5e5e5\n"
	".custom_blendshapes\n"
	"    mesh_morph_weights @array_float = 0 1 0.25 0 0.85 0.4\n"
	"\n"
	"[interactive_synth_console type=MusicPuzzle]\n"
	"parent @string = station_master\n"
	"id @string = d4e5f6a7b8c\n"
	"enabled @bool = true\n"
	".transform\n"
	"    position @vec3 = 0 1.1 14.5\n"
	"    rotation @vec4 = -0.258 0 0 0.966\n"
	"    scale @vec3 = 1.2 1 1\n"
	".audio_engine\n"
	"    base_frequency_hz @float = 110\n"
	"    chord_progression @array_string = Am7\x1f" "D9\x1f" "Gmaj7\x1f" "Cmaj7\n"
	"    step_sequencer_gate @array_int = 1 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1\n"
	"    filter_cutoff_points @array_float = 220 440 880 1760 3520\n"
	"    ..synth_parameters\n"
	"        oscillator_type @string = polyphonic_sawtooth\n"
	"        detune_cents @float = 14.25\n"
	"        attack_decay_sustain_release @vec4 = 0.04 0.25 0.65 0.35\n"
	"        vibrato_lfo_speed @float = 6.2\n"
	"\n"
	"[deck_door_light type=PointLight]\n"
	"parent @string = station_master\n"
	"id @string = f9e8d7c6b5a\n"
	"enabled @bool = false\n"
	".transform\n"
	"    position @vec3 = -12 4.2 8\n"
	"    rotation @vec4 = 0 0 0 1\n"
	"    scale @vec3 = 1 1 1\n"
	".light_properties\n"
	"    radius @float = 8.5\n"
	"    color @vec3 = 1 0.02 0.05\n"
	"    intensity @float = 12\n";
}