-- Particle System Configuration

return {
    format = "particle_system",
    emitters = {
        {
            startColor = {
                [3] = 0.5,
                [1] = 0.5,
                [2] = 0.5,
                [4] = 0.6,
            },
            speed = {
                0.5,
                1.5,
            },
            looping = true,
            rotationSpeed = {
                0,
                0,
            },
            name = "Smoke",
            useTexture = false,
            randomizeStartColor = false,
            direction = {
                [3] = 0,
                [1] = 0,
                [2] = 1,
            },
            endSize = {
                1,
                2,
            },
            drag = 0.5,
            gravity = {
                [3] = 0,
                [1] = 0,
                [2] = 0.2,
            },
            startColorRangeMin = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
                [4] = 1,
            },
            directionRandomness = 0.3,
            startColorRangeMax = {
                [3] = 1,
                [1] = 1,
                [2] = 1,
                [4] = 1,
            },
            startRotation = {
                0,
                360,
            },
            texturePath = "",
            startSize = {
                0.3,
                0.5,
            },
            endColor = {
                [3] = 0.3,
                [1] = 0.3,
                [2] = 0.3,
                [4] = 0,
            },
            shape = "sphere",
            maxParticles = 10000,
            emissionMode = "continuous",
            enabled = true,
            emissionRate = 468,
            shapeSize = {
                [3] = 0.5,
                [1] = 0.5,
                [2] = 0.5,
            },
            coneAngle = 45,
            duration = 5,
            localOffset = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
            },
            localRotation = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
            },
            lifetime = {
                2,
                4,
            },
            additiveBlending = false,
        },
        {
            startColor = {
                [3] = 0.2,
                [1] = 1,
                [2] = 0.8,
                [4] = 1,
            },
            speed = {
                2,
                4,
            },
            looping = true,
            rotationSpeed = {
                0,
                0,
            },
            name = "Fire",
            useTexture = false,
            randomizeStartColor = false,
            direction = {
                [3] = 0,
                [1] = 0,
                [2] = 1,
            },
            endSize = {
                0.05,
                0.1,
            },
            drag = 0.2,
            gravity = {
                [3] = 0,
                [1] = 0,
                [2] = 1,
            },
            startColorRangeMin = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
                [4] = 1,
            },
            directionRandomness = 0,
            startColorRangeMax = {
                [3] = 1,
                [1] = 1,
                [2] = 1,
                [4] = 1,
            },
            startRotation = {
                0,
                360,
            },
            texturePath = "",
            startSize = {
                0.2,
                0.4,
            },
            endColor = {
                [3] = 0,
                [1] = 1,
                [2] = 0.2,
                [4] = 0,
            },
            shape = "cone",
            maxParticles = 10000,
            emissionMode = "continuous",
            enabled = true,
            emissionRate = 836.5,
            shapeSize = {
                [3] = 1,
                [1] = 1,
                [2] = 1,
            },
            coneAngle = 45,
            duration = 5,
            localOffset = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
            },
            localRotation = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
            },
            lifetime = {
                0.5,
                1.5,
            },
            additiveBlending = true,
        },
        {
            startColor = {
                [3] = 0.5,
                [1] = 1,
                [2] = 0.9,
                [4] = 1,
            },
            speed = {
                5,
                10,
            },
            startSize = {
                0.05,
                0.1,
            },
            looping = false,
            bursts = {
                {
                    cycleInterval = 0.5,
                    time = 0,
                    count = 50,
                },
            },
            useTexture = false,
            endColor = {
                [3] = 0,
                [1] = 1,
                [2] = 0.5,
                [4] = 0,
            },
            drag = 0,
            direction = {
                [3] = 0,
                [1] = 0,
                [2] = 1,
            },
            endSize = {
                0.01,
                0.02,
            },
            gravity = {
                [3] = 0,
                [1] = 0,
                [2] = -15,
            },
            randomizeStartColor = false,
            startColorRangeMin = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
                [4] = 1,
            },
            directionRandomness = 1,
            startColorRangeMax = {
                [3] = 1,
                [1] = 1,
                [2] = 1,
                [4] = 1,
            },
            startRotation = {
                0,
                360,
            },
            texturePath = "",
            name = "Sparks",
            rotationSpeed = {
                0,
                0,
            },
            shape = "point",
            maxParticles = 10000,
            emissionMode = "burst",
            enabled = true,
            emissionRate = 10,
            shapeSize = {
                [3] = 1,
                [1] = 1,
                [2] = 1,
            },
            coneAngle = 45,
            duration = 0.1,
            localOffset = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
            },
            localRotation = {
                [3] = 0,
                [1] = 0,
                [2] = 0,
            },
            lifetime = {
                0.3,
                0.8,
            },
            additiveBlending = true,
        },
    },
}
