if(NOT DEFINED ROOT_DIR)
    message(FATAL_ERROR "sync_api_headers: ROOT_DIR not set")
endif()

set(SRC_DIR "${ROOT_DIR}/src")
set(INCLUDE_DIR "${ROOT_DIR}/include")

set(NOTICE [=[// ============================================================
// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Changes will not persist
// ============================================================]=])

if(NOT IS_DIRECTORY "${SRC_DIR}")
    message(STATUS "sync_api_headers: src dir not found: ${SRC_DIR}")
    return()
endif()

if(EXISTS "${INCLUDE_DIR}")
    file(REMOVE_RECURSE "${INCLUDE_DIR}")
endif()
file(MAKE_DIRECTORY "${INCLUDE_DIR}")

file(GLOB_RECURSE HEADER_FILES "${SRC_DIR}/*.h" "${SRC_DIR}/*.hpp")
set(PUBLIC_HEADERS)

foreach(header IN LISTS HEADER_FILES)
    file(READ "${header}" CONTENT)
    if(CONTENT MATCHES "TOAST_API")
        list(APPEND PUBLIC_HEADERS "${header}")
    endif()
endforeach()

set(FOUND_DEPENDENCY TRUE)
while(FOUND_DEPENDENCY)
    set(FOUND_DEPENDENCY FALSE)
    foreach(header IN LISTS PUBLIC_HEADERS)
        file(READ "${header}" CONTENT)
        get_filename_component(header_dir "${header}" DIRECTORY)
        string(REGEX MATCHALL "#include[ \t]+[<\"]([^>\"]+\\.(h|hpp|inl))[>\"]" INCLUDE_MATCHES "${CONTENT}")
        foreach(include_match IN LISTS INCLUDE_MATCHES)
            string(REGEX REPLACE "^#include[ \t]+[<\"]([^>\"]+)[>\"].*" "\\1" include_path "${include_match}")
            if(include_path MATCHES "^toast/")
                set(dependency "${SRC_DIR}/${include_path}")
            else()
                set(dependency "${header_dir}/${include_path}")
            endif()
            cmake_path(NORMAL_PATH dependency)
            if(EXISTS "${dependency}")
                list(FIND PUBLIC_HEADERS "${dependency}" dependency_index)
                if(dependency_index EQUAL -1)
                    list(APPEND PUBLIC_HEADERS "${dependency}")
                    set(FOUND_DEPENDENCY TRUE)
                endif()
            endif()
        endforeach()
    endforeach()
endwhile()

foreach(header IN LISTS PUBLIC_HEADERS)
    file(READ "${header}" CONTENT)
    file(RELATIVE_PATH REL_PATH "${SRC_DIR}" "${header}")
    set(dst_path "${INCLUDE_DIR}/${REL_PATH}")
    get_filename_component(dst_dir "${dst_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${dst_dir}")
    file(WRITE "${dst_path}" "${NOTICE}\n${CONTENT}")
endforeach()
