/**
 * @file Reflect.hpp
 * @author Xein
 * @date 24 May 2026
 *
 * @brief Runtime reflection system for Nodes
 */

#pragma once

#include <any>
#include <array>
#include <cassert>
#include <cstdint>
#include <nlohmann/json.hpp>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <toast/export.hpp>
#include <toast/log.hpp>
#include <type_traits>
#include <typeinfo>
#include <unordered_map>
#include <utility>

namespace toast {

class Node;

/**
 * @brief Bit-flag set describing which lifecycle phases a Node type implements
 *
 * Used by the scheduler to build wave assignments and by the code generator to populate
 * TickFunctions::list. tick_mask is the subset that executes every frame.
 */
enum class TickFunctionList : uint16_t {
	none = 0,
	pre_init = 1 << 1,
	init = 1 << 2,
	destroy = 1 << 3,
	begin = 1 << 4,
	end = 1 << 5,
	on_enable = 1 << 6,
	on_disable = 1 << 7,
	early_tick = 1 << 8,
	tick = 1 << 9,
	post_physics = 1 << 10,
	late_tick = 1 << 11,
	load = 1 << 12,
	save = 1 << 13,
	tick_mask = early_tick | tick | post_physics | late_tick,
	all = 0xFFFF,
};

/**
 * @brief Serialization kind for a reflected field
 *
 * Determines how the generated accessor reads and writes the field value across the
 * FFI boundary and how the inspector widget renders the field.
 */
enum class FieldType : uint8_t {
	bool_t,
	int_t,
	float_t,
	string_t,
	double_t,
	uid_t,
	vec2_t,
	vec3_t,
	vec4_t,
	quaternion_t,
};

// Bitwise operators for TickFunctionList
constexpr auto operator&(TickFunctionList lhs, TickFunctionList rhs) -> TickFunctionList {
	return static_cast<TickFunctionList>(static_cast<uint16_t>(lhs) & static_cast<uint16_t>(rhs));
}

constexpr auto operator|(TickFunctionList lhs, TickFunctionList rhs) -> TickFunctionList {
	return static_cast<TickFunctionList>(static_cast<uint16_t>(lhs) | static_cast<uint16_t>(rhs));
}

constexpr auto operator&=(TickFunctionList& lhs, TickFunctionList rhs) -> TickFunctionList& {
	lhs = lhs & rhs;
	return lhs;
}

constexpr auto operator|=(TickFunctionList& lhs, TickFunctionList rhs) -> TickFunctionList& {
	lhs = lhs | rhs;
	return lhs;
}

// Helper to check if a flag is set
constexpr auto hasFlag(TickFunctionList flags, TickFunctionList flag) -> bool {
	return (flags & flag) == flag;
}

/**
 * @brief Set of lifecycle function pointers for one Node type
 *
 * Generated by the reflection tool; one pointer per lifecycle phase. A null pointer means
 * the type does not implement that phase. The list bitfield mirrors the non-null pointers
 * for O(1) phase-presence checks without dereferencing.
 *
 * @note Do not call these directly; go through Node::callTick()
 */
struct TickFunctions {
	/// void* erases the Node* to avoid a vtable; generated code casts it back before calling
	using Invoker = void (*)(void*);

	TickFunctionList list;

	Invoker load = nullptr;
	Invoker save = nullptr;
	Invoker pre_init = nullptr;
	Invoker init = nullptr;
	Invoker destroy = nullptr;
	Invoker begin = nullptr;
	Invoker end = nullptr;
	Invoker on_enable = nullptr;
	Invoker on_disable = nullptr;
	Invoker early_tick = nullptr;
	Invoker tick = nullptr;
	Invoker post_physics = nullptr;
	Invoker late_tick = nullptr;
};

/**
 * @brief Runtime descriptor for one reflected field
 *
 * Holds type metadata, JSON attributes parsed from the header annotation (e.g. Group, Name),
 * and a type-erased getter/setter pair that works without knowing the concrete Node subtype.
 *
 * @note The getter returns std::any; the setter silently does nothing on a type mismatch
 */
struct TOAST_API FieldInfo {
	using FieldGetterPtr = std::any (*)(void*);
	using FieldSetterPtr = void (*)(void*, std::any);

	std::string_view name;
	std::string_view type;    // C++ type name
	FieldType value_type;     // serialization kind
	nlohmann::json attributes;
	bool is_array = false;    // True if field is vector

	FieldGetterPtr get;
	FieldSetterPtr set;

	/// Returns the value of the "Group" annotation, or an empty string if not present
	[[nodiscard]]
	auto groupName() const -> std::string {
		return getAttribute("Group");
	}

	/**
	 * @brief Checks whether a JSON annotation key is present on this field
	 * @param attr_name The annotation key, e.g. "Group" or "Name"
	 * @return true if the attribute exists, regardless of its value
	 */
	[[nodiscard]]
	auto hasAttribute(std::string_view attr_name) const -> bool {
		return attributes.contains(std::string(attr_name));
	}

	/**
	 * @brief Returns the first string value of a JSON annotation
	 * @param attr_name The annotation key to look up
	 * @return The first string element, or an empty string if the key is absent or has no elements
	 */
	[[nodiscard]]
	auto getAttribute(std::string_view attr_name) const -> std::string {
		auto it = attributes.find(std::string(attr_name));
		if (it == attributes.end() || it->empty()) {
			return "";
		}
		return it->at(0).get<std::string>();
	}
};

/**
 * @brief A named sub-section of fields inside a GroupInfo
 *
 * Corresponds to a nested category in the inspector. Fields inside a subgroup are
 * displayed collapsed under the subgroup label.
 */
struct TOAST_API SubgroupInfo {
	std::string_view name;
	std::span<const FieldInfo* const> fields;

	/**
	 * @brief Linear scan for a field by name within this subgroup
	 * @param field_name The reflected field name to look up
	 * @return Pointer to the matching FieldInfo, or nullptr if not found
	 */
	[[nodiscard]]
	auto getField(std::string_view field_name) const -> const FieldInfo* {
		for (const auto& f : fields) {
			if (field_name == f->name) {
				return f;
			}
		}
		return nullptr;
	}
};

/**
 * @brief Top-level category grouping fields and optional SubgroupInfo children
 *
 * Corresponds to a collapsible section in the inspector. Fields with no Group annotation
 * have an empty group name and are placed in a default section by the inspector.
 */
struct TOAST_API GroupInfo {
	std::string_view name;
	std::span<const FieldInfo* const> fields;
	std::span<const SubgroupInfo> subgroups;

	/**
	 * @brief Finds a subgroup by name
	 * @param group_name The subgroup name to look up
	 * @return Pointer to the matching SubgroupInfo, or nullptr if not found
	 */
	[[nodiscard]]
	auto getSubgroup(std::string_view group_name) const -> const SubgroupInfo* {
		for (const auto& g : subgroups) {
			if (group_name == g.name) {
				return &g;
			}
		}
		return nullptr;
	}

	/**
	 * @brief Finds a field by name within this group's flat field list
	 * @param field_name The reflected field name to look up
	 * @return Pointer to the matching FieldInfo, or nullptr if not found
	 * @note Does not search inside subgroups; use NodeInfo::getField() for a full search
	 */
	[[nodiscard]]
	auto getField(std::string_view field_name) const -> const FieldInfo* {
		for (const auto& f : fields) {
			if (field_name == f->name) {
				return f;
			}
		}
		return nullptr;
	}
};

/**
 * @brief Runtime descriptor for one parameter of a reflected function
 */
struct TOAST_API ParameterInfo {
	std::string_view name;
	std::string_view type;            // C++ type name, as spelled in the header
	std::optional<std::string_view> default_value;
	const std::type_info* type_id;    // typeid(std::decay_t<param>), for call-time validation
};

/**
 * @brief Runtime descriptor for one reflected member function
 *
 * @note Do not call invoke directly; go through NodeInfo::call()
 */
struct TOAST_API FunctionInfo {
	/// Generic erased trampoline pointer; reinterpret_cast back to the real signature before calling
	using Invoker = void (*)();

	std::string_view name;
	std::string_view return_type;            // C++ return type name, as spelled in the header
	const std::type_info* return_type_id;    // typeid(std::decay_t<return>), for call-time validation
	std::span<const ParameterInfo> parameters;
	Invoker invoke = nullptr;
};

/**
 * @brief Complete reflection record for a registered Node type
 *
 * Populated by the generated Reflect<T> specialization at program startup.
 * base_type chains through C++ inheritance so that field lookups and isA() checks
 * traverse the full type hierarchy without RTTI.
 *
 * @note NodeInfo instances are static globals; comparing two NodeInfo pointers for equality
 *       is a valid way to test for identical types
 */
struct TOAST_API NodeInfo {
	using Factory = Node* (*)();
	using Deleter = void (*)(Node*);

	std::string_view type;
	const NodeInfo* base_type;
	std::span<const FieldInfo> all_fields;
	std::span<const FieldInfo* const> fields;
	std::span<const GroupInfo> groups;
	std::span<const FunctionInfo> methods;

	TickFunctions functions;

	Factory construct = nullptr;
	Deleter destroy = nullptr;

	/**
	 * @brief Finds a field by name in this type's all_fields, then walks base_type if not found
	 * @param field_name The reflected field name to look up
	 * @return Pointer to the matching FieldInfo, or nullptr if the field is not reflected anywhere in the hierarchy
	 */
	[[nodiscard]]
	auto getField(std::string_view field_name) const -> const FieldInfo* {
		for (const auto& f : all_fields) {
			if (field_name == f.name) {
				return &f;
			}
		}
		if (base_type) {
			return base_type->getField(field_name);
		}
		return nullptr;
	}

	/**
	 * @brief Finds a reflected function by name in this type, then walks base_type if not found
	 * @param method_name The reflected function name to look up
	 * @return Pointer to the matching FunctionInfo, or nullptr if the function is not reflected anywhere in the hierarchy
	 */
	[[nodiscard]]
	auto getMethod(std::string_view method_name) const -> const FunctionInfo* {
		for (const auto& m : methods) {
			if (method_name == m.name) {
				return &m;
			}
		}
		if (base_type) {
			return base_type->getMethod(method_name);
		}
		return nullptr;
	}

	/**
	 * @brief Looks up a reflected function by name and invokes it on the given object
	 * @tparam R The function's return type; defaults to void
	 * @tparam Args Deduced argument types, forwarded to the function
	 * @param obj The object to call the function on; must be an instance of this type or a subtype
	 * @param method_name The reflected function name to call
	 * @param args Arguments forwarded to the function
	 * @return The function's return value, or a default-constructed R if the function is not found
	 */
	template<typename R = void, typename... Args>
	auto call(void* obj, std::string_view method_name, Args&&... args) const -> R {
		const FunctionInfo* fn = getMethod(method_name);

		if (!fn) {
			TOAST_WARN("Reflect", "call(): reflected function '{}' not found on '{}'", method_name, type);
			assert(false && "NodeInfo::call(): reflected function not found");
			if constexpr (std::is_void_v<R>) {
				return;
			} else {
				return R {};
			}
		}

		bool signature_ok = fn->parameters.size() == sizeof...(Args) && fn->return_type_id != nullptr &&
		                    *fn->return_type_id == typeid(std::decay_t<R>);
		if (signature_ok) {
			const std::array<const std::type_info*, sizeof...(Args)> expected = {&typeid(std::decay_t<Args>)...};
			for (std::size_t i = 0; i < expected.size(); ++i) {
				if (fn->parameters[i].type_id == nullptr || *fn->parameters[i].type_id != *expected[i]) {
					signature_ok = false;
					break;
				}
			}
		}
		if (!signature_ok) {
			TOAST_WARN("Reflect", "call(): signature mismatch for '{}' on '{}'; invoking is undefined behavior", method_name, type);
			assert(false && "NodeInfo::call(): argument or return type mismatch");
		}

		using Trampoline = R (*)(void*, std::decay_t<Args>...);
		auto* trampoline = reinterpret_cast<Trampoline>(fn->invoke);
		return trampoline(obj, std::forward<Args>(args)...);
	}

	/**
	 * @brief Checks whether this type is the same as or a subtype of another
	 * @param other The NodeInfo to test against
	 * @return true if this type's inheritance chain passes through other; equivalent to dynamic_cast but without RTTI
	 */
	[[nodiscard]]
	auto isA(const NodeInfo* other) const -> bool {
		for (const NodeInfo* cur = this; cur; cur = cur->base_type) {
			if (cur == other) {
				return true;
			}
		}
		return false;
	}

	/**
	 * @brief Checks whether this type or any base type implements the given lifecycle phase(s)
	 * @param mask A TickFunctionList bitflag; use tick_mask to check for any per-frame phase
	 * @return true if any bit in mask is set in functions.list anywhere in the inheritance chain
	 */
	[[nodiscard]]
	auto hasFunction(TickFunctionList mask) const -> bool {
		for (const NodeInfo* cur = this; cur; cur = cur->base_type) {
			if ((cur->functions.list & mask) != TickFunctionList::none) {
				return true;
			}
		}
		return false;
	}

	/// FNV-1a hash of the type string; not the same as a Node's runtime UID
	[[nodiscard]]
	constexpr auto id() const -> uint32_t {
		uint32_t hash = 2166136261u;
		for (char c : type) {
			hash ^= static_cast<uint8_t>(c);
			hash *= 16777619u;
		}
		return hash;
	}

	/**
	 * @brief Finds a group by name, walking base_type if not found
	 * @param group_name The group name to look up
	 * @return Pointer to the matching GroupInfo, or nullptr if no such group exists in this type or its bases
	 */
	[[nodiscard]]
	auto getGroup(std::string_view group_name) const -> const GroupInfo* {
		for (const auto& g : groups) {
			if (group_name == g.name) {
				return &g;
			}
		}
		if (base_type) {
			return base_type->getGroup(group_name);
		}
		return nullptr;
	}

	/**
	 * @brief Finds a field by name, walking the full inheritance chain
	 * @param field_name The reflected field name to look up
	 * @return Pointer to the matching FieldInfo, or nullptr if not found
	 * @note Prefer getField() for new code; this is an alias kept for backwards compatibility
	 */
	[[nodiscard]]
	auto search(std::string_view field_name) const -> const FieldInfo* {
		for (const auto& f : all_fields) {
			if (field_name == f.name) {
				return &f;
			}
		}
		if (base_type) {
			return base_type->search(field_name);
		}
		return nullptr;
	}

	/**
	 * @brief Calls fn for each NodeInfo in the inheritance chain, from the root base down to this type
	 * @param fn Callable taking a const NodeInfo&; called once per type in base-first order
	 * @note Useful for collecting all fields including inherited ones without duplicates
	 */
	template<typename F>
	void forEachBaseType(F&& fn) const {
		if (base_type) {
			base_type->forEachBaseType(fn);
		}
		fn(*this);
	}
};

template<class T>
class Reflect;

/**
 * @brief Member-robber pattern used by the generated reflection code
 *
 * A Robber<Tag,Ptr> static instance runs at startup and writes the private member pointer Ptr
 * into the public Accessor<Tag>::member. This is the only standards-conforming way to obtain a
 * pointer-to-private-member at compile time without modifying the Node class header.
 *
 * @note This namespace is an implementation detail; user code should never reference it directly
 */
namespace _detail {
template<typename Tag>
struct Accessor {
	inline static typename Tag::type member;
};

template<typename Tag, typename Tag::type Ptr>
struct Robber {
	Robber() { Accessor<Tag>::member = Ptr; }

	static Robber instance;
};

template<typename Tag, typename Tag::type Ptr>
Robber<Tag, Ptr> Robber<Tag, Ptr>::instance;
}

/**
 * @brief Generated getter/setter pair binding a private member pointer to the FieldInfo interface
 *
 * Produced by the reflection code generator using the Robber pattern in toast::_detail.
 * Allows the inspector and serialization layer to read and write private fields without
 * modifying the Node class header.
 *
 * @tparam Class The Node subtype that owns the field
 * @tparam FieldType The C++ type of the field
 * @tparam Tag Tag type that holds the pointer-to-member via Accessor<Tag>::member
 */
template<class Class, typename FieldType, typename Tag>
struct FieldAccess {
	static auto get(void* obj) -> std::any { return static_cast<Class*>(obj)->*_detail::template Accessor<Tag>::member; }

	static void set(void* obj, std::any value) {
		if (auto* typed = std::any_cast<FieldType>(&value)) {
			static_cast<Class*>(obj)->*_detail::template Accessor<Tag>::member = *typed;
		}
	}
};

/**
 * @brief Global registry mapping fully-qualified type names to NodeInfo pointers
 *
 * The singleton is populated by registerEngineTypes(), which is generated by refgen and called
 * at engine startup. After startup the registry is read-only from user code.
 *
 * @note Do not call registerNode() directly; it is reserved for generated registration functions
 * @see NodeInfo, registerEngineTypes()
 */
class TOAST_API NodeRegistry {
public:
	NodeRegistry() { instance = this; }

	/// Called by the generated registration function; inserts a type into the registry
	static void registerNode(const NodeInfo* info) { (*instance).types[info->type] = info; }

	/**
	 * @brief Looks up a Node type by its fully-qualified C++ name
	 * @param name Fully-qualified class name, e.g. "toast::Node3D"
	 * @return Pointer to the static NodeInfo, or nullptr if the type was not registered
	 */
	[[nodiscard]]
	static auto reflect(std::string_view name) -> const NodeInfo* {
		auto it = (*instance).types.find(name);
		return it != (*instance).types.end() ? it->second : nullptr;
	}

private:
	std::unordered_map<std::string_view, const NodeInfo*> types;
	static inline NodeRegistry* instance = nullptr;
};

TOAST_API void registerEngineTypes();

}
