name: build-windows-release

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: build-windows-release-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: build windows release
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build (Windows)
        run: xmake f -m release -y && xmake --all -y
