name: ci-build-windows

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-build-windows-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-windows-msvc:
    name: build windows msvc ${{ matrix.build_type }}
    runs-on: [ self-hosted, windows ]
    strategy:
      matrix:
        build_type: [ debug, release ]
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup vcpkg
        id: vcpkg
        uses: ./.github/actions/setup-vcpkg

      - name: Build
        run: |
          cmake -B build/windows-msvc-${{ matrix.build_type }} `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type == 'debug' && 'Debug' || 'Release' }} `
            -DCMAKE_C_COMPILER=cl `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_TOOLCHAIN_FILE="${{ steps.vcpkg.outputs.toolchain-file }}" `
            -DVCPKG_TARGET_TRIPLET=x64-windows
          cmake --build build/windows-msvc-${{ matrix.build_type }} --target dummy_game

  test-windows-debug:
    name: test windows debug
    needs: build-windows-msvc
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup vcpkg
        id: vcpkg
        uses: ./.github/actions/setup-vcpkg

      - name: Run tests
        env:
          TRACY_NO_INVARIANT_CHECK: "1"
        run: |
          cmake -B build/windows-test-debug `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Debug `
            -DCMAKE_C_COMPILER=cl `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_TOOLCHAIN_FILE="${{ steps.vcpkg.outputs.toolchain-file }}" `
            -DVCPKG_TARGET_TRIPLET=x64-windows
          cmake --build build/windows-test-debug --target toast_tests
          ctest --test-dir build/windows-test-debug --verbose

  test-windows-release:
    name: test windows release
    needs: build-windows-msvc
    if: github.base_ref == 'main'
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup vcpkg
        id: vcpkg
        uses: ./.github/actions/setup-vcpkg

      - name: Run tests
        env:
          TRACY_NO_INVARIANT_CHECK: "1"
        run: |
          cmake -B build/windows-test-release `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_C_COMPILER=cl `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_TOOLCHAIN_FILE="${{ steps.vcpkg.outputs.toolchain-file }}" `
            -DVCPKG_TARGET_TRIPLET=x64-windows
          cmake --build build/windows-test-release --target toast_tests
          ctest --test-dir build/windows-test-release --verbose




