name: test-linux

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: test-linux-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: test linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests (Linux)
        run: |
          eval "$(nix --extra-experimental-features 'nix-command flakes' print-dev-env .)"
          xmake f -m debug -y
          xmake test -y
